import { useContext, useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react'
import { Link } from 'react-router-dom'
import { Building2, CheckCheck, Download, FileUp, Plus, ShieldCheck, X } from 'lucide-react'
import { getBlob, ref, uploadBytes } from 'firebase/storage'
import { Button } from '@/components/ui/button'
import { useCompany } from '@/hooks/useCompany'
import { CompanyRecordsPreview, useCompanyRecords } from '@/hooks/useCompanyRecords'
import { storage } from '@/lib/firebase'
import { money, today, type Books } from '@/lib/accounting'
import { bankLedgerLines, excludeClearedOpeningLines, findBankDuplicateCandidates, suggestBankMatches, validateStatementBalances, validateStatementRows, type BankBookLine, type BankStatementRow } from '@/lib/bank-reconciliation'
import { importBankStatementRows, normalizeBankAmount, suggestBankColumnMapping, type BankColumnMapping } from '@/lib/bank-statement-import'
import { readBankStatement, type BankStatementReading } from '@/lib/read-bank-statement'
import { BANK_WORKFLOW_LIMITS, type BankAccountRecord, type BankAdjustment, type BankStatement, type BankStatementInput, type CompanyBankRequest } from '@/lib/bank-workflow'

const fieldClass = 'w-full rounded-md border border-input bg-card px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-ring'
const panel = 'rounded-xl border border-border bg-card p-5 sm:p-6'
const decimal = (value: number | null) => value === null ? '' : (value / 100).toFixed(2)
function amount(value: string) { if (!value.trim()) return null; const parsed = normalizeBankAmount(value); if (parsed.value === undefined) throw Error(parsed.issue); return parsed.value }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="grid gap-1.5 text-sm font-medium"><span>{label}</span>{children}</label> }
function Modal({ title, busy, close, children, error }: { title: string; busy: boolean; close: () => void; children: ReactNode; error?: string }) {
  const dialog = useRef<HTMLDialogElement>(null)
  useEffect(() => { dialog.current?.showModal(); const node = dialog.current; return () => node?.close() }, [])
  return <dialog ref={dialog} aria-label={title} onCancel={e => { e.preventDefault(); if (!busy) close() }} className="ubb-modal m-auto max-h-[92svh] w-[min(97vw,1200px)] overflow-auto rounded-2xl border border-border bg-card p-5 text-foreground shadow-xl backdrop:bg-slate-950/40 sm:p-7"><div className="mb-5 flex justify-between gap-4"><h2 className="text-xl font-semibold">{title}</h2><Button type="button" variant="ghost" size="icon" disabled={busy} onClick={close} aria-label="Close bank dialog"><X size={18} /></Button></div>{error && <p role="alert" className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}{children}</dialog>
}
function download(name: string, content: Blob) { const url = URL.createObjectURL(content), link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000) }
function exportStatement(statement: BankStatement) { download(`bank-reconciliation-${statement.id}.json`, new Blob([JSON.stringify(statement, null, 2)], { type: 'application/json' })) }
type Send = (request: CompanyBankRequest, success: string) => Promise<Record<string, unknown> | null>

export function BankWorkspace() {
  const company = useCompany(), member = company?.membership, allowed = Boolean(member?.active && member.role !== 'viewer')
  const preview = useContext(CompanyRecordsPreview)
  const versions = useCompanyRecords<BankStatement>('bankStatementVersions', allowed)
  const accounts = useCompanyRecords<BankAccountRecord>('bankAccounts', allowed), statements = useCompanyRecords<BankStatement>('bankStatements', allowed), adjustments = useCompanyRecords<BankAdjustment>('bankAdjustments', allowed)
  const [accountId, setAccountId] = useState(''), [statementId, setStatementId] = useState(''), [modal, setModal] = useState<'account' | 'account-edit' | 'import' | 'edit' | 'matches' | null>(null)
  const [importBusy, setImportBusy] = useState(false)
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [reviewNote, setReviewNote] = useState('')
  const account = accounts.rows.find(row => row.id === accountId), statement = statements.rows.find(row => row.id === statementId && row.bankId === accountId)
  const canReview = Boolean(member && ['admin', 'manager'].includes(member.role))
  useEffect(() => { setAccountId(''); setStatementId(''); setModal(null); setError(''); setNotice('') }, [member?.companyId, member?.uid, member?.role])
  async function send(request: CompanyBankRequest, success: string) {
    if (!company || busy || !allowed) return null
    setBusy(true); setError(''); setNotice('')
    try { const result = await company.invoke('companyBank', { ...request }); setNotice(result.alreadyImported ? 'This file was already imported for this bank. The existing statement has been opened; no duplicate import was created.' : success); return result }
    catch (cause) { setError(cause instanceof Error ? cause.message : 'The bank action could not be completed.'); return null }
    finally { setBusy(false) }
  }
  async function sourceFile() { if (!statement) return; if (preview) { setNotice('Original files are unavailable in this isolated preview.'); return } try { download(statement.file.name, await getBlob(ref(storage, statement.file.path))) } catch { setError('The original statement could not be downloaded. Check company access and connection.') } }
  if (!company || !allowed) return <section className={panel}><ShieldCheck className="size-8 text-primary" /><h2 className="mt-4 text-lg font-semibold">Private bank reconciliation</h2><p className="mt-2 text-sm text-muted-foreground">Company Admins, Accounting Managers and Accountants can access bank statements and reconciliation records.</p></section>
  if (accounts.loading || statements.loading || adjustments.loading || !company.booksReady) return <p role="status" className={panel}>Loading bank accounts and company records…</p>
  const loadError = accounts.error || statements.error || adjustments.error
  if (loadError) return <p role="alert" className={panel}>{loadError}</p>
  const visible = statements.rows.filter(row => row.bankId === accountId).sort((a, b) => b.to.localeCompare(a.to)), pending = adjustments.rows.filter(row => row.statementId === statementId && row.status === 'pending')
  return <div className="space-y-5">
    <div className="rounded-xl border border-primary/15 bg-accent/50 p-5"><div className="flex gap-3"><Building2 className="mt-0.5 size-6 shrink-0 text-primary" /><div><h2 className="font-semibold">Your bank statement, connected to your books</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">Read CSV, Excel or PDF statements, review extracted transactions, then match recorded receipts and payments. Matching creates no extra journal entry. A different Admin or Manager reviews the completed reconciliation.</p></div></div></div>
    {error && <p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</p>}{notice && <p role="status" className="rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">{notice}</p>}
    <section className={panel}><div className="flex flex-wrap items-end gap-3"><div className="min-w-64 flex-1"><Field label="Company bank account"><select className={fieldClass} value={accountId} onChange={e => { setAccountId(e.target.value); setStatementId('') }}><option value="">Choose a bank account</option>{accounts.rows.map(row => <option key={row.id} value={row.id}>{row.name} · {row.bankName} · …{row.accountSuffix}{row.active ? '' : ' · Archived'}</option>)}</select></Field></div><Button variant="outline" onClick={() => setModal('account')} disabled={busy || !canReview}><Plus size={16} />Add bank account</Button><Button variant="outline" disabled={!account || busy || !canReview} onClick={() => setModal('account-edit')}>Edit bank account</Button><Button disabled={!account?.active || busy} onClick={() => setModal('import')}><FileUp size={16} />Upload statement</Button></div>{account && <p className="mt-3 text-xs text-muted-foreground">Linked account {account.accountCode} · PHP · Up to {BANK_WORKFLOW_LIMITS.rows} transactions and 10 MB per saved statement. Each bank account uses its own cash ledger account.</p>}{!accounts.rows.length && <p className="mt-6 text-sm text-muted-foreground">Add your first bank account to start. Create a separate cash account in the <Link className="text-primary underline" to="/accounting/accounts">chart of accounts</Link> for each bank account.</p>}</section>
    {account && <div className="grid gap-5 xl:grid-cols-[280px_minmax(0,1fr)]"><aside className={panel}><h2 className="font-semibold">Statements</h2><div className="mt-4 space-y-2">{visible.map(row => <button key={row.id} className={`w-full rounded-lg border p-3 text-left text-sm ${row.id === statementId ? 'border-primary bg-accent' : 'border-border hover:bg-muted/50'}`} onClick={() => { setStatementId(row.id); setReviewNote('') }}><span className="block font-semibold">{row.reference}</span><span className="mt-1 block text-xs text-muted-foreground">{row.from} – {row.to}</span><span className="mt-2 block capitalize">{row.status} · {row.rows.length} transactions</span></button>)}{!visible.length && <p className="text-sm leading-6 text-muted-foreground">Upload the original bank statement. Extracted transactions will appear here for review and matching.</p>}</div></aside>
      {statement ? <section className={`${panel} min-w-0 space-y-5`}><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-lg font-semibold">{statement.reference}</h2><p className="mt-1 text-sm text-muted-foreground">{statement.from} to {statement.to} · <span className="capitalize">{statement.status}</span> · Version {statement.version}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={sourceFile}><Download size={15} />Original</Button><Button size="sm" variant="outline" onClick={() => exportStatement(statement)}><Download size={15} />Export record</Button></div></div>
        <div className="grid gap-3 sm:grid-cols-3">{[['Opening bank balance', statement.openingBalance], ['Closing bank balance', statement.closingBalance], ['Transactions to review', statement.rows.filter(row => row.issues.length || !row.date || row.amount === null).length]] .map(([label, value], index) => <div key={String(label)} className="rounded-lg bg-muted/50 p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-lg font-semibold tabular-nums">{index === 2 ? value : value === null ? 'Needs review' : money(value as number)}</p></div>)}</div>
        <div className="flex flex-wrap gap-2">{statement.status === 'draft' && <><Button variant="outline" disabled={busy} onClick={() => setModal('edit')}>Review statement rows</Button><Button disabled={busy} onClick={() => setModal('matches')}><CheckCheck size={16} />Match transactions</Button></>}<Link className="self-center text-sm text-primary underline" to="/accounting/receivable">Record a missing collection</Link><Link className="self-center text-sm text-primary underline" to="/accounting/payable">Record a missing supplier payment</Link></div>
        <StatementTable rows={statement.rows} />
        <details className="rounded-lg border p-4"><summary className="cursor-pointer text-sm font-semibold">Retained statement history</summary><div className="mt-3 space-y-2">{versions.rows.filter(row => row.id.startsWith(`${statement.id}-`)).sort((a, b) => b.version - a.version).map(row => <div key={row.id} className="flex flex-wrap items-center justify-between gap-2 text-xs"><span>Version {row.version} · {row.status} · {row.updatedAt} · {row.reviewNote || 'Initial import'}</span><Button size="sm" variant="outline" onClick={() => exportStatement(row)}>Export version {row.version}</Button></div>)}{versions.error && <p role="alert">{versions.error}</p>}</div></details>
        {statement.report && <Report statement={statement} />}
        {!!pending.length && <div className="space-y-3 rounded-lg border p-4"><h3 className="font-semibold">Bank adjustments awaiting review</h3>{pending.map(row => <AdjustmentReview key={row.id} row={row} canReview={canReview} busy={busy} uid={member!.uid} booksRevision={company.revision} send={send} />)}</div>}
        <div className="space-y-3 border-t pt-5"><Field label={statement.status === 'approved' ? 'Reason for controlled reopening' : 'Reconciliation review note'}><textarea className={fieldClass} rows={3} maxLength={2000} value={reviewNote} onChange={e => setReviewNote(e.target.value)} placeholder="Record the balance checks, outstanding items and any corrections reviewed." /></Field>
          {statement.status === 'draft' && <Button disabled={busy || reviewNote.trim().length < 10} onClick={() => send({ action: 'prepare', id: statement.id, expectedVersion: statement.version, note: reviewNote }, 'Reconciliation prepared for independent review.')} >Prepare reconciliation</Button>}
          {statement.status === 'prepared' && <><p className="text-sm text-muted-foreground">The statement is frozen while awaiting review. Approval checks the current ledger and locks the reconciled bank period.</p><Button disabled={busy || !canReview || statement.preparedBy === member?.uid || reviewNote.trim().length < 10} onClick={() => send({ action: 'approve', id: statement.id, expectedVersion: statement.version, expectedBooksRevision: company.revision, note: reviewNote }, 'Reconciliation approved. Bank transactions through this period are protected.')} >Approve reconciliation</Button>{statement.preparedBy === member?.uid && <p className="text-xs text-amber-800">Another Admin or Manager must approve your reconciliation.</p>}</>}
          {statement.status !== 'draft' && canReview && <Button className="ml-2" variant="outline" disabled={busy || reviewNote.trim().length < 10} onClick={() => send({ action: 'reopen', id: statement.id, expectedVersion: statement.version, note: reviewNote }, 'Statement reopened with its previous report retained in history.')} >Reopen with reason</Button>}
        </div>
      </section> : <section className={`${panel} flex min-h-64 items-center justify-center text-sm text-muted-foreground`}>Select a statement to review its transactions and reconciliation.</section>}
    </div>}
    {modal === 'account' && <Modal error={error} title="Add company bank account" busy={busy} close={() => setModal(null)}><BankAccountForm books={company.books} accounts={accounts.rows} busy={busy} save={async value => { const result = await send({ action: 'saveAccount', expectedVersion: 0, value }, 'Bank account linked to the company books.'); if (result) { setAccountId(String(result.id)); setModal(null) } }} /></Modal>}
    {modal === 'account-edit' && account && <Modal error={error} title="Edit company bank account" busy={busy} close={() => setModal(null)}><BankAccountForm key={account.id} initial={account} books={company.books} accounts={accounts.rows} busy={busy} save={async value => { const result = await send({ action: 'saveAccount', id: account.id, expectedVersion: account.version, value }, 'Bank account details saved. Existing statement and payment history are retained.'); if (result) setModal(null) }} /></Modal>}
    {modal === 'import' && account && <Modal error={error} title="Read bank statement" busy={busy || importBusy} close={() => setModal(null)}><StatementImporter processing={setImportBusy} preview={Boolean(preview)} key={account.id} account={account} books={company.books} companyId={member!.companyId} existing={statements.rows.filter(row => row.bankId === account.id)} busy={busy} send={send} done={id => { setStatementId(id); setModal(null) }} /></Modal>}
    {modal === 'edit' && statement && account && <Modal error={error} title="Review imported transactions" busy={busy} close={() => setModal(null)}><SavedStatementEditor statement={statement} account={account} books={company.books} busy={busy} send={send} done={() => setModal(null)} /></Modal>}
    {modal === 'matches' && statement && account && <Modal error={error} title="Match bank transactions" busy={busy} close={() => setModal(null)}><MatchingEditor statement={statement} account={account} statements={statements.rows} books={company.books} busy={busy} send={send} done={() => setModal(null)} /></Modal>}
  </div>
}

function BankAccountForm({ books, accounts, busy, save, initial }: { initial?: BankAccountRecord; books: Books; accounts: BankAccountRecord[]; busy: boolean; save: (value: Omit<BankAccountRecord, 'id' | 'version' | 'createdBy' | 'createdAt' | 'updatedBy' | 'updatedAt'>) => Promise<void> }) {
  const [form, setForm] = useState(initial ? { name: initial.name, bankName: initial.bankName, accountSuffix: initial.accountSuffix, accountCode: initial.accountCode, currency: initial.currency, active: initial.active } : { name: '', bankName: '', accountSuffix: '', accountCode: '', currency: 'PHP' as const, active: true })
  return <form onSubmit={e => { e.preventDefault(); void save(form) }} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2">{([['name', 'Account label'], ['bankName', 'Bank name'], ['accountSuffix', 'Last 1–8 account characters']] as const).map(([key, label]) => <Field key={key} label={label}><input className={fieldClass} required maxLength={key === 'accountSuffix' ? 8 : 150} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} /></Field>)}<Field label="Cash or bank ledger account"><select className={fieldClass} required disabled={!!initial} value={form.accountCode} onChange={e => setForm({ ...form, accountCode: e.target.value })}><option value="">Choose unlinked cash account</option>{books.accounts.filter(a => a.cash && a.type === 'Asset' && (a.code === initial?.accountCode || !accounts.some(row => row.accountCode === a.code))).map(a => <option key={a.code} value={a.code}>{a.code} · {a.name}</option>)}</select></Field></div><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.active} onChange={e => setForm({ ...form, active: e.target.checked })} />Active for new statements and payments</label><p className="text-sm text-muted-foreground">Only the account suffix is stored here. This release reconciles PHP accounts.</p><Button type="submit" disabled={busy}>Save bank account</Button></form>
}

function StatementTable({ rows }: { rows: BankStatementRow[] }) { return <div className="max-h-96 overflow-auto rounded-lg border"><table className="w-full text-left text-xs"><thead className="sticky top-0 bg-muted"><tr>{['Date', 'Description / reference', 'Money in', 'Money out', 'Balance', 'Source / review'].map(label => <th key={label} className="p-3 font-medium">{label}</th>)}</tr></thead><tbody className="divide-y">{rows.map(row => <tr key={row.id}><td className="whitespace-nowrap p-3">{row.date || 'Review date'}</td><td className="min-w-48 p-3">{row.description}<p className="text-muted-foreground">{row.reference}</p></td><td className="whitespace-nowrap p-3">{row.amount !== null && row.amount > 0 ? money(row.amount) : '—'}</td><td className="whitespace-nowrap p-3">{row.amount !== null && row.amount < 0 ? money(-row.amount) : '—'}</td><td className="whitespace-nowrap p-3">{row.balance === null ? '—' : money(row.balance)}</td><td className="min-w-40 p-3">{row.source.sheet ? `${row.source.sheet} · ` : ''}{row.source.page ? `Page ${row.source.page} · ` : ''}Row {row.source.row}{row.issues.map((item, index) => <p key={index} className="mt-1 text-amber-800">{item.message}</p>)}</td></tr>)}</tbody></table></div> }

function StatementFields({ value, change, priorLines }: { value: BankStatementInput; change: (value: BankStatementInput) => void; priorLines: BankBookLine[] }) {
  const [opening, setOpening] = useState(decimal(value.openingBalance)), [closing, setClosing] = useState(decimal(value.closingBalance)), [error, setError] = useState('')
  const moneyChange = (raw: string, key: 'openingBalance' | 'closingBalance') => { (key === 'openingBalance' ? setOpening : setClosing)(raw); try { change({ ...value, [key]: amount(raw), openingReviewed: key === 'openingBalance' ? false : value.openingReviewed }); setError('') } catch (e) { change({ ...value, [key]: null, openingReviewed: key === 'openingBalance' ? false : value.openingReviewed }); setError((e as Error).message) } }
  return <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-3"><Field label="Statement reference"><input required maxLength={150} className={fieldClass} value={value.reference} onChange={e => change({ ...value, reference: e.target.value })} /></Field><Field label="Period start"><input type="date" required className={fieldClass} value={value.from} onChange={e => change({ ...value, from: e.target.value, openingReviewed: false, openingOutstandingLineIds: [] })} /></Field><Field label="Period end"><input type="date" required className={fieldClass} value={value.to} onChange={e => change({ ...value, to: e.target.value })} /></Field><Field label="Opening bank balance (PHP)"><input className={fieldClass} inputMode="decimal" value={opening} onChange={e => moneyChange(e.target.value, 'openingBalance')} /></Field><Field label="Closing bank balance (PHP)"><input className={fieldClass} inputMode="decimal" value={closing} onChange={e => moneyChange(e.target.value, 'closingBalance')} /></Field><Field label="Statement row order"><select className={fieldClass} value={value.order} onChange={e => change({ ...value, order: e.target.value as BankStatementInput['order'] })}><option value="ascending">Oldest first</option><option value="descending">Newest first</option></select></Field></div>{error && <p role="alert" className="text-sm text-red-700">{error}</p>}
    <details className="rounded-lg border p-4"><summary className="cursor-pointer text-sm font-semibold">Opening reconciliation review</summary><p className="mt-3 text-sm leading-6 text-muted-foreground">For the first reconciliation, select cash entries dated before this statement that were still outstanding at its start. Other prior entries are treated as already cleared. The system checks these against the statement opening balance. Later periods carry forward the previous approved reconciliation.</p><div className="mt-3 max-h-44 overflow-auto space-y-2">{priorLines.map(line => <label key={line.id} className="flex gap-2 text-xs"><input type="checkbox" checked={value.openingOutstandingLineIds.includes(line.id)} onChange={e => change({ ...value, openingReviewed: false, openingOutstandingLineIds: e.target.checked ? [...value.openingOutstandingLineIds, line.id] : value.openingOutstandingLineIds.filter(id => id !== line.id) })} /><span>{line.date} · {line.reference} · {money(line.amount)} · {line.description}</span></label>)}{!priorLines.length && <p className="text-xs text-muted-foreground">No cash entries precede this statement period.</p>}</div><label className="mt-4 flex gap-2 text-sm"><input type="checkbox" checked={value.openingReviewed} onChange={e => change({ ...value, openingReviewed: e.target.checked })} /><span>I checked the opening statement balance and outstanding entries.</span></label></details>
  </div>
}

const emptyStatement = (): BankStatementInput => ({ reference: '', from: `${today().slice(0, 7)}-01`, to: today(), openingBalance: null, closingBalance: null, order: 'ascending', rows: [], openingReviewed: false, openingOutstandingLineIds: [] })
function StatementImporter({ account, books, companyId, existing, busy, send, done, processing, preview }: { processing: (busy: boolean) => void; preview: boolean; account: BankAccountRecord; books: Books; companyId: string; existing: BankStatement[]; busy: boolean; send: Send; done: (id: string) => void }) {
  const fixtures = useContext(CompanyRecordsPreview)?.bankPreviewFiles as { name: string; text: string }[] | undefined
  const [file, setFile] = useState<File | null>(null), [reading, setReading] = useState<BankStatementReading | null>(null), [sheet, setSheet] = useState(0), [mapping, setMapping] = useState<Partial<BankColumnMapping>>({}), [value, setValue] = useState(emptyStatement)
  const [repopulation, setRepopulation] = useState(0), [saving, setSaving] = useState(false), [reviewNote, setReviewNote] = useState('')
  const mounted = useRef(true)
  const [progress, setProgress] = useState(''), [error, setError] = useState(''), [reviewed, setReviewed] = useState(false), [working, setWorking] = useState(false), [forceOcr, setForceOcr] = useState(false), [headerRow, setHeaderRow] = useState(''), [delimiter, setDelimiter] = useState('')
  const controller = useRef<AbortController | null>(null), savedFile = useRef<{ source: File; metadata: BankStatementReading['file'] & { path: string } } | null>(null)
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; controller.current?.abort() } }, [])
  useEffect(() => { processing(saving); return () => processing(false) }, [processing, saving])
  const table = reading?.tables[sheet]
  const duplicateCount = findBankDuplicateCandidates(value.rows, existing.flatMap(row => row.rows)).length
  async function read(selected: File, replaceRows = false) {
    controller.current?.abort(); const activeRead = new AbortController(); controller.current = activeRead; setWorking(true); setError(''); setReviewed(false)
    try { const result = await readBankStatement(selected, { signal: activeRead.signal, forceOcr, onProgress: setProgress, ...(headerRow ? { headerRow: Number(headerRow) } : {}), ...(delimiter ? { delimiter } : {}) }); if (controller.current !== activeRead || activeRead.signal.aborted) return; setFile(selected); setReading(result); setSheet(0); const initial = suggestBankColumnMapping(result.tables[0]).mapping; setMapping(initial); if (replaceRows || !value.rows.length) populate(result, 0, initial); setProgress('Statement read. Review the columns and source details.') }
    catch (cause) { if (controller.current === activeRead) { setError(cause instanceof Error ? cause.message : 'The statement could not be read.'); setProgress('') } }
    finally { if (controller.current === activeRead) setWorking(false) }
  }
  function populate(result: BankStatementReading, index: number, chosen: Partial<BankColumnMapping>) { setReviewed(false); try { const t = result.tables[index], rows = importBankStatementRows(t, chosen as BankColumnMapping, { idPrefix: result.sha256.slice(0, 32) + '-' + index }); if (rows.length > BANK_WORKFLOW_LIMITS.rows) throw Error(`This file contains ${rows.length} transactions. Split it into statement periods of at most ${BANK_WORKFLOW_LIMITS.rows} rows.`); const dates = rows.flatMap(row => row.date ? [row.date] : []).sort(); setValue(old => ({ ...old, reference: old.reference || result.file.name, rows, from: dates[0] || old.from, to: dates.at(-1) || old.to, openingBalance: t.metadata.openingBalance ? amount(t.metadata.openingBalance) : old.openingBalance, closingBalance: t.metadata.closingBalance ? amount(t.metadata.closingBalance) : old.closingBalance, openingReviewed: false, openingOutstandingLineIds: [] })); setRepopulation(n => n + 1); setError(''); setReviewed(false) } catch (cause) { setError((cause as Error).message) } }
  async function save(e: FormEvent) { e.preventDefault(); if (!file || !reading || !reviewed || working || reviewNote.trim().length < 10) return; setError(''); setWorking(true); setSaving(true); processing(true); try { validateStatementRows(value.rows, { allowUnresolved: true }); let metadata = savedFile.current?.source === file ? savedFile.current.metadata : undefined; if (!metadata) { metadata = { ...reading.file, path: `companies/${companyId}/bank-statements/${crypto.randomUUID()}` }; if (!(import.meta.env.DEV && preview)) await uploadBytes(ref(storage, metadata.path), file, { contentType: metadata.type }); if (!mounted.current) return; savedFile.current = { source: file, metadata } } if (!mounted.current) return; const result = await send({ action: 'importStatement', bankId: account.id, file: metadata, input: value, reviewNote }, 'Bank statement saved with populated transactions. Resolve flagged rows before reconciliation.'); if (result && mounted.current) done(String(result.id)) } catch (cause) { if (mounted.current) setError((cause as Error).message) } finally { if (mounted.current) { setWorking(false); setSaving(false) } processing(false) } }
  return <form className="space-y-5" onSubmit={save}><fieldset disabled={working || busy} className="space-y-5"><p className="text-sm leading-6 text-muted-foreground">Choose the original CSV, XLSX or PDF. Scanned PDF pages are read locally. Review the bank account, dates and amounts before saving. {BANK_WORKFLOW_LIMITS.rows} transactions per statement; 10 MB maximum; PDFs up to 10 pages.</p><div className="flex flex-wrap gap-2">{import.meta.env.DEV && preview && fixtures?.map(fixture => <Button key={fixture.name} type="button" variant="outline" disabled={working || busy} onClick={() => { setReading(null); setValue(emptyStatement()); savedFile.current = null; void read(new File([fixture.text], fixture.name, { type: 'text/csv' }), true) }}>Read sample {fixture.name}</Button>)}</div><div className="grid gap-3 sm:grid-cols-3"><Field label="Bank statement file"><input type="file" accept=".csv,.xlsx,.pdf" className={fieldClass} disabled={working || busy} onChange={e => { const selected = e.target.files?.[0]; if (selected) { setReading(null); setValue(emptyStatement()); setFile(selected); savedFile.current = null; void read(selected, true) } }} /></Field><Field label="CSV header row (optional)"><input type="number" min={1} max={100} className={fieldClass} value={headerRow} onChange={e => setHeaderRow(e.target.value)} /></Field><Field label="CSV delimiter"><select className={fieldClass} value={delimiter} onChange={e => setDelimiter(e.target.value)}><option value="">Detect automatically</option><option value=",">Comma</option><option value=";">Semicolon</option><option value={'\t'}>Tab</option><option value="|">Pipe</option></select></Field></div><div className="flex flex-wrap gap-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={forceOcr} onChange={e => setForceOcr(e.target.checked)} />Read PDF as scanned pages</label>{file && <Button type="button" variant="outline" disabled={working || busy} onClick={() => read(file)}>Read again</Button>}</div>{progress && <p role="status" className="text-sm text-primary">{progress}</p>}
    {reading && table && <><div className="rounded-lg bg-muted/50 p-4 text-sm"><b>{reading.file.name}</b> · {table.rows.length} source rows{reading.pages ? ` · ${reading.pages} pages` : ''}{reading.ocr ? ' · OCR used' : ''}{reading.warnings.map((warning, index) => <p key={index} className="mt-2 text-amber-800">{warning}</p>)}{Object.entries(table.metadata).map(([key, entry]) => <p key={key} className="mt-1">Source {key}: {entry}</p>)}</div><div className="grid gap-3 sm:grid-cols-3"><Field label="Worksheet"><select className={fieldClass} value={sheet} onChange={e => { setReviewed(false); const index = Number(e.target.value); setSheet(index); setMapping(suggestBankColumnMapping(reading.tables[index]).mapping) }}>{reading.tables.map((entry, index) => <option key={index} value={index}>{entry.headerSource.sheet || `Table ${index + 1}`}</option>)}</select></Field><Field label="Amount columns"><select className={fieldClass} value={mapping.amountMode || ''} onChange={e => { setReviewed(false); setMapping({ ...mapping, amountMode: e.target.value as BankColumnMapping['amountMode'] }) }}><option value="">Choose convention</option><option value="signed">Signed amount: money in positive</option><option value="debit_credit">Separate debit and credit columns</option><option value="direction">Amount plus debit/credit direction</option></select></Field><Field label="Date order"><select className={fieldClass} value={mapping.dateOrder || 'auto'} onChange={e => { setReviewed(false); setMapping({ ...mapping, dateOrder: e.target.value as BankColumnMapping['dateOrder'] }) }}><option value="auto">Flag ambiguous dates</option><option value="DMY">Day / month / year</option><option value="MDY">Month / day / year</option><option value="YMD">Year / month / day</option></select></Field>{(['date', 'description', 'reference', 'amount', 'debit', 'credit', 'balance', 'direction'] as const).map(key => <Field key={key} label={`${key[0].toUpperCase() + key.slice(1)} column`}><select className={fieldClass} value={mapping[key] ?? ''} onChange={e => { setReviewed(false); setMapping(old => { const next = { ...old }; if (e.target.value === '') delete next[key]; else next[key] = Number(e.target.value); return next }) }}><option value="">Not mapped</option>{table.headers.map((header, index) => <option key={index} value={index}>{index + 1} · {header}</option>)}</select></Field>)}</div><Button type="button" variant="outline" disabled={working || busy} onClick={() => populate(reading, sheet, mapping)}>{value.rows.length ? 'Replace rows using reviewed columns' : 'Populate transaction rows'}</Button>{value.rows.length > 0 && <p className="text-xs text-muted-foreground">Reading again preserves current rows. Replacing rows discards unsaved row corrections.</p>}</>}
    {!!value.rows.length && <><StatementFields key={`fields-${repopulation}`} value={value} change={next => { setValue(next); setReviewed(false) }} priorLines={bankLedgerLines(books, account.accountCode).filter(line => line.date < value.from)} /><div className="rounded-lg border p-4 text-sm">{value.rows.length} populated transactions · {value.rows.filter(row => row.issues.length || !row.date || row.amount === null).length} need review · {duplicateCount} possible duplicates</div><StatementRowsEditor key={`rows-${repopulation}`} allowExclude={false} rows={value.rows} change={rows => { setValue({ ...value, rows }); setReviewed(false) }} /><Field label="Source review and correction notes"><textarea required minLength={10} maxLength={2000} className={fieldClass} rows={3} value={reviewNote} onChange={e => setReviewNote(e.target.value)} placeholder="Record the source account, period and any corrected values checked against the original." /></Field><label className="flex gap-2 text-sm leading-6"><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)} /><span>I checked that the source belongs to {account.bankName}, account ending {account.accountSuffix}, in PHP, and reviewed the populated rows. Flagged values will remain unresolved until corrected.</span></label></>}
    {error && <p role="alert" className="text-sm text-red-700">{error}</p>}<Button type="submit" disabled={busy || working || !reviewed || !value.rows.length || reviewNote.trim().length < 10}>Save populated statement</Button></fieldset>{working && !saving && <Button type="button" variant="outline" onClick={() => controller.current?.abort()}>Cancel reading</Button>}</form>
}

function StatementRowsEditor({ rows, change, allowExclude = true }: { allowExclude?: boolean; rows: BankStatementRow[]; change: (rows: BankStatementRow[]) => void }) {
  const [selected, setSelected] = useState(''), [error, setError] = useState(''), [rawAmount, setRawAmount] = useState(''), [rawBalance, setRawBalance] = useState('')
  const row = rows.find(value => value.id === selected)
  function select(id: string) { setSelected(id); const entry = rows.find(value => value.id === id); setRawAmount(decimal(entry?.amount ?? null)); setRawBalance(decimal(entry?.balance ?? null)); setError('') }
  function patch(values: Partial<BankStatementRow>) { change(rows.map(entry => entry.id === selected ? { ...entry, ...values } : entry)) }
  return <div className="space-y-3"><StatementTable rows={rows} /><Field label="Correct or review a source row"><select className={fieldClass} value={selected} onChange={e => select(e.target.value)}><option value="">Choose a transaction</option>{rows.map(entry => <option key={entry.id} value={entry.id}>Row {entry.source.row} · {entry.date || 'Date unclear'} · {entry.description.slice(0, 80)}{entry.issues.length ? ' · Needs review' : ''}</option>)}</select></Field>{row && <div className="space-y-3 rounded-lg border border-primary/25 bg-accent/20 p-4"><p className="break-words text-xs text-muted-foreground">Original: {row.source.text || JSON.stringify(row.raw)}</p><div className="grid gap-3 sm:grid-cols-3"><Field label="Reviewed date"><input type="date" className={fieldClass} value={row.date || ''} onChange={e => patch({ date: e.target.value || null })} /></Field><Field label="Reviewed amount (PHP; withdrawals negative)"><input className={fieldClass} value={rawAmount} onChange={e => { setRawAmount(e.target.value); try { patch({ amount: amount(e.target.value) }); setError('') } catch (cause) { patch({ amount: null }); setError((cause as Error).message) } }} /></Field><Field label="Reviewed running balance (optional)"><input className={fieldClass} value={rawBalance} onChange={e => { setRawBalance(e.target.value); try { patch({ balance: amount(e.target.value) }); setError('') } catch (cause) { patch({ balance: null }); setError((cause as Error).message) } }} /></Field><Field label="Reviewed description"><input className={fieldClass} maxLength={1000} value={row.description} onChange={e => patch({ description: e.target.value })} /></Field><Field label="Reviewed reference"><input className={fieldClass} maxLength={200} value={row.reference} onChange={e => patch({ reference: e.target.value })} /></Field></div><div className="flex flex-wrap gap-2"><Button type="button" variant="outline" onClick={() => { try { validateStatementRows([{ ...row, issues: [] }]); patch({ issues: [] }); setError('') } catch (cause) { setError((cause as Error).message) } }}>Accept reviewed row</Button>{allowExclude && <Button type="button" variant="outline" onClick={() => { change(rows.filter(entry => entry.id !== row.id)); setSelected('') }}>Exclude non-transaction row</Button>}</div><p className="text-xs text-muted-foreground">{allowExclude ? 'Exclusions retain the previous saved version and require a correction reason.' : 'Save the initial import before excluding non-transaction rows. This retains their original values and the reason for exclusion in history.'}</p>{error && <p role="alert" className="text-sm text-red-700">{error}</p>}</div>}</div>
}

function SavedStatementEditor({ statement, account, books, busy, send, done }: { statement: BankStatement; account: BankAccountRecord; books: Books; busy: boolean; send: Send; done: () => void }) {
  const [version] = useState(statement.version), [value, setValue] = useState<BankStatementInput>({ reference: statement.reference, from: statement.from, to: statement.to, openingBalance: statement.openingBalance, closingBalance: statement.closingBalance, order: statement.order, rows: statement.rows, openingReviewed: statement.openingReviewed, openingOutstandingLineIds: statement.openingOutstandingLineIds }), [note, setNote] = useState('')
  let balanceIssues: string[] = []; try { balanceIssues = validateStatementBalances(value).issues.map(item => item.message) } catch (e) { balanceIssues = [(e as Error).message] }
  return <form className="space-y-5" onSubmit={async e => { e.preventDefault(); if (await send({ action: 'saveStatement', id: statement.id, expectedVersion: version, input: value, reviewNote: note }, 'Statement corrections saved with the previous version retained.')) done() }}><StatementFields value={value} change={setValue} priorLines={bankLedgerLines(books, account.accountCode).filter(line => line.date < value.from)} /><StatementRowsEditor rows={value.rows} change={rows => setValue({ ...value, rows })} />{!!balanceIssues.length && <div className="rounded-lg bg-amber-50 p-4 text-sm text-amber-900">{[...new Set(balanceIssues)].map(issue => <p key={issue}>{issue}</p>)}</div>}<Field label="Reason for row corrections or exclusions"><textarea required minLength={10} maxLength={2000} rows={3} className={fieldClass} value={note} onChange={e => setNote(e.target.value)} /></Field>{statement.allocations.length > 0 && <p className="text-sm text-amber-800">Clear saved matches before changing statement rows. Their original source data remains protected.</p>}{version !== statement.version && <p role="alert" className="text-sm text-amber-800">Another user changed this statement. Your edits are preserved here; close and reopen to load the latest version.</p>}<Button type="submit" disabled={busy || note.trim().length < 10 || version !== statement.version || !!statement.allocations.length}>Save reviewed corrections</Button></form>
}

function MatchingEditor({ statement, account, statements, books, busy, send, done }: { statement: BankStatement; account: BankAccountRecord; statements: BankStatement[]; books: Books; busy: boolean; send: Send; done: () => void }) {
  const [version] = useState(statement.version), [allocations, setAllocations] = useState(statement.allocations), [rowId, setRowId] = useState(statement.rows[0]?.id || ''), [lineId, setLineId] = useState(''), [allocated, setAllocated] = useState(''), [error, setError] = useState('')
  const [offsetAccount, setOffsetAccount] = useState(''), [adjustmentReference, setAdjustmentReference] = useState(''), [adjustmentDescription, setAdjustmentDescription] = useState('')
  const lines = excludeClearedOpeningLines(bankLedgerLines(books, account.accountCode, statement.to), statement, statements), row = statement.rows.find(value => value.id === rowId)
  const elsewhere = statements.filter(value => value.bankId === statement.bankId && value.id !== statement.id).flatMap(value => value.allocations)
  const allAllocations = [...elsewhere, ...allocations], lineUsed = (id: string) => allAllocations.filter(a => a.bookLineId === id).reduce((sum, a) => sum + a.amount, 0)
  const signedMatched = (id: string) => allocations.filter(a => a.bankRowId === id).reduce((sum, a) => sum + Math.sign(lines.find(line => line.id === a.bookLineId)?.amount || 0) * a.amount, 0)
  const suggestions = row ? suggestBankMatches(row, lines, allAllocations) : []
  function add(bookLineId: string, cents: number) { if (!row || !Number.isSafeInteger(cents) || cents <= 0) { setError('Choose a positive allocation amount.'); return } if (allocations.some(a => a.bankRowId === row.id && a.bookLineId === bookLineId)) { setError('This pair is already linked. Remove its allocation to replace the amount.'); return } setAllocations([...allocations, { bankRowId: row.id, bookLineId, amount: cents }]); setError('') }
  async function adjustment() { if (!row) return; const result = await send({ action: 'prepareAdjustment', statementId: statement.id, expectedVersion: version, input: { bankRowId: row.id, date: row.date || '', reference: adjustmentReference, description: adjustmentDescription, offsetAccount } }, 'Bank adjustment prepared for another Admin or Manager. The ledger is unchanged until approval.'); if (result) done() }
  return <div className="space-y-5"><p className="text-sm leading-6 text-muted-foreground">Allocate recorded cash movements to statement transactions. Splits and grouped net deposits can use several lines. Receipt and payment records are linked without posting them again.</p><Field label="Bank transaction"><select className={fieldClass} value={rowId} onChange={e => { setRowId(e.target.value); setLineId(''); setAllocated('') }}>{statement.rows.map(value => <option key={value.id} value={value.id}>{value.date || 'Date unresolved'} · {value.description.slice(0, 75)} · {value.amount === null ? 'Amount unresolved' : money(value.amount)} · Remaining {value.amount === null ? '?' : money(value.amount - signedMatched(value.id))}</option>)}</select></Field>
    {row && <div className="space-y-4 rounded-lg border p-4"><p className="text-sm font-semibold">{row.description} · {row.reference}</p>{row.issues.length > 0 && <p className="text-sm text-amber-800">Resolve this row’s source issues before matching.</p>}<div className="space-y-2">{suggestions.slice(0, 5).map(suggestion => { const line = lines.find(value => value.id === suggestion.bookLineId); return line && <button type="button" key={line.id} disabled={busy || row.issues.length > 0} className="flex w-full flex-wrap justify-between gap-2 rounded-lg bg-muted/50 p-3 text-left text-xs hover:bg-accent" onClick={() => add(line.id, suggestion.amount)}><span>{line.date} · {line.reference} · {money(line.amount)}<span className="mt-1 block text-muted-foreground">{suggestion.reasons.join(' · ')}</span></span><span className="font-semibold text-primary">Add suggested link</span></button> })}</div><div className="grid gap-3 sm:grid-cols-[1fr_180px_auto]"><Field label="Recorded bank ledger line"><select className={fieldClass} value={lineId} onChange={e => { setLineId(e.target.value); const line = lines.find(value => value.id === e.target.value); setAllocated(line ? decimal(Math.abs(line.amount) - lineUsed(line.id)) : '') }}><option value="">Choose recorded cash movement</option>{lines.filter(line => Math.abs(line.amount) > lineUsed(line.id)).map(line => <option key={line.id} value={line.id}>{line.date} · {line.reference} · {money(line.amount)} · {line.description}</option>)}</select></Field><Field label="Allocation (PHP)"><input className={fieldClass} inputMode="decimal" value={allocated} onChange={e => setAllocated(e.target.value)} /></Field><Button type="button" className="self-end" variant="outline" disabled={!lineId || busy || row.issues.length > 0} onClick={() => { try { add(lineId, amount(allocated) || 0) } catch (cause) { setError((cause as Error).message) } }}>Add link</Button></div>
      <details className="rounded-lg border p-4"><summary className="cursor-pointer text-sm font-medium">Missing bank charge or interest entry</summary><p className="mt-3 text-sm leading-6 text-muted-foreground">Use this for a new bank fee or interest entry. For customer collections or supplier payments, use the corresponding receipt/payment action, then match it here. The adjustment amount is the unmatched statement amount and requires independent approval.</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Adjustment offset account"><select className={fieldClass} value={offsetAccount} onChange={e => setOffsetAccount(e.target.value)}><option value="">Choose expense or income account</option>{books.accounts.filter(value => ['Expense', 'Revenue'].includes(value.type) && !value.cash).map(value => <option key={value.code} value={value.code}>{value.code} · {value.name}</option>)}</select></Field><Field label="Adjustment reference"><input className={fieldClass} maxLength={150} value={adjustmentReference} onChange={e => setAdjustmentReference(e.target.value)} /></Field><Field label="Adjustment description and basis"><input className={fieldClass} maxLength={500} value={adjustmentDescription} onChange={e => setAdjustmentDescription(e.target.value)} /></Field></div><Button type="button" className="mt-3" variant="outline" disabled={busy || !offsetAccount || !adjustmentReference.trim() || adjustmentDescription.trim().length < 10 || JSON.stringify(allocations) !== JSON.stringify(statement.allocations) || row.issues.length > 0} onClick={adjustment}>Prepare bank adjustment</Button><p className="mt-2 text-xs text-muted-foreground">Save or discard any match edits before preparing an adjustment.</p></details>
    </div>}
    <div className="max-h-60 overflow-auto rounded-lg border"><table className="w-full text-left text-xs"><thead className="bg-muted"><tr><th className="p-3">Bank row</th><th className="p-3">Ledger reference</th><th className="p-3">Allocated</th><th /></tr></thead><tbody>{allocations.map((a, index) => <tr key={`${a.bankRowId}:${a.bookLineId}`} className="border-t"><td className="p-3">{statement.rows.find(value => value.id === a.bankRowId)?.description}</td><td className="p-3">{lines.find(value => value.id === a.bookLineId)?.reference || a.bookLineId}</td><td className="p-3">{money(a.amount)}</td><td className="p-3"><button className="text-red-700" onClick={() => setAllocations(allocations.filter((_, i) => i !== index))}>Remove link</button></td></tr>)}</tbody></table>{!allocations.length && <p className="p-5 text-sm text-muted-foreground">No links selected. Imported rows remain separate from the books.</p>}</div>{error && <p role="alert" className="text-sm text-red-700">{error}</p>}{version !== statement.version && <p role="alert" className="text-sm text-amber-800">The statement changed. Close and reopen to review current matches.</p>}<div className="flex gap-3"><Button disabled={busy || version !== statement.version} onClick={async () => { if (await send({ action: 'saveMatches', id: statement.id, expectedVersion: version, allocations }, 'Reviewed transaction links saved. No new ledger entries were created.')) done() }}>Save matches</Button><Button variant="outline" onClick={() => setAllocations([])}>Clear selected links</Button></div></div>
}

function Report({ statement }: { statement: BankStatement }) { const r = statement.report!; return <div className="space-y-4 rounded-lg border border-primary/20 bg-accent/20 p-5"><h3 className="font-semibold">Reconciliation as of {r.asOf}</h3><div className="grid gap-3 sm:grid-cols-3">{[['Statement closing balance', r.bankBalance], ['Deposits in transit', r.outstandingDeposits], ['Outstanding payments', r.outstandingPayments], ['Adjusted bank balance', r.adjustedBankBalance], ['Book balance', r.bookBalance], ['Remaining difference', r.difference]].map(([label, value]) => <div key={String(label)}><p className="text-xs text-muted-foreground">{label}</p><p className={`mt-1 font-semibold tabular-nums ${label === 'Remaining difference' && value !== 0 ? 'text-red-700' : ''}`}>{money(value as number)}</p></div>)}</div>{r.outstandingBookLines.length > 0 && <details><summary className="cursor-pointer text-sm">Outstanding book items ({r.outstandingBookLines.length})</summary><div className="mt-3 space-y-2 text-xs">{r.outstandingBookLines.map(line => <p key={line.id}>{line.date} · {line.reference} · {line.description} · {money(line.remaining)}</p>)}</div></details>}<p className="text-xs text-muted-foreground">Books revision {r.booksRevision} · {statement.status === 'approved' ? 'Approved report retained with its source versions.' : 'Prepared report; approval rechecks the current books.'}</p></div> }
function AdjustmentReview({ row, canReview, uid, booksRevision, busy, send }: { row: BankAdjustment; canReview: boolean; uid: string; booksRevision: number; busy: boolean; send: Send }) { const [note, setNote] = useState(''); return <div className="space-y-3 rounded-lg bg-muted/40 p-4"><p className="text-sm font-semibold">{row.reference} · {money(row.amount)}</p><p className="text-sm">{row.description} · {row.date} · Offset {row.offsetAccount}</p><Field label={`Review note for ${row.reference}`}><input className={fieldClass} maxLength={2000} value={note} onChange={e => setNote(e.target.value)} /></Field><div className="flex gap-2"><Button size="sm" disabled={busy || !canReview || uid === row.createdBy || note.trim().length < 10} onClick={() => send({ action: 'approveAdjustment', id: row.id, expectedVersion: row.version, expectedBooksRevision: booksRevision, note }, 'Bank adjustment approved, posted and matched atomically.')} >Approve and post</Button><Button size="sm" variant="outline" disabled={busy || !canReview || note.trim().length < 10} onClick={() => send({ action: 'rejectAdjustment', id: row.id, expectedVersion: row.version, note }, 'Bank adjustment rejected; no journal was posted.')} >Reject</Button></div>{uid === row.createdBy && <p className="text-xs text-muted-foreground">A different Admin or Manager must approve your adjustment.</p>}</div> }
