import { useContext, useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react'
import { Link } from 'react-router-dom'
import { Banknote, CheckCircle2, ClipboardCheck, Download, FileCheck2, Plus, ShieldCheck, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { useCompany } from '@/hooks/useCompany'
import { CompanyRecordsPreview, useCompanyRecords } from '@/hooks/useCompanyRecords'
import { cents, isReversed, money, outstanding, today, type Books } from '@/lib/accounting'
import { validBankDate } from '@/lib/bank-reconciliation'
import { type BankAccountRecord, type BankStatement } from '@/lib/bank-workflow'
import { paymentClearance, type CompanyPaymentRequest, type PaymentMethod, type PaymentRequest, type PaymentRequestInput } from '@/lib/payment-workflow'
import { saveSettlementEvidence, SettlementEvidence, SettlementEvidenceList, type PendingSettlementEvidence } from './SettlementEvidence'
import { SupplierBillPdfLink } from './SupplierBillPdf'

const input = 'w-full rounded-md border border-input bg-card px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-ring'
const panel = 'rounded-xl border border-border bg-card p-5 sm:p-6'
const statusLabels: Record<PaymentRequest['status'], string> = { pending: 'Awaiting approval', approved: 'Approved · awaiting release', released: 'Released', rejected: 'Rejected', cancelled: 'Cancelled' }
const clearanceLabels = { not_released: 'Not released', outstanding: 'Outstanding at bank', partially_cleared: 'Partially cleared', cleared: 'Cleared at bank', reversed: 'Payment reversed', unavailable: 'Source needs review' }
type History = PaymentRequest & { requestId: string; changeAction: string }
type Send = (request: CompanyPaymentRequest, message: string) => Promise<Record<string, unknown>>
function useMounted() { const mounted=useRef(true); useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[]); return mounted }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="grid gap-1.5 text-sm font-medium"><span>{label}</span>{children}</label> }
function Modal({ title, busy, close, children }: { title: string; busy: boolean; close: () => void; children: ReactNode }) {
  const dialog = useRef<HTMLDialogElement>(null)
  useEffect(() => { dialog.current?.showModal(); const node = dialog.current; return () => node?.close() }, [])
  return <dialog ref={dialog} aria-label={title} onCancel={event => { event.preventDefault(); if (!busy) close() }} className="ubb-modal m-auto max-h-[92svh] w-[min(97vw,1100px)] overflow-auto rounded-2xl border border-border bg-card p-5 text-foreground shadow-xl backdrop:bg-slate-950/40 sm:p-7"><div className="mb-5 flex justify-between gap-4"><h2 className="text-xl font-semibold">{title}</h2><Button type="button" size="icon" variant="ghost" aria-label="Close payment dialog" disabled={busy} onClick={close}><X size={18}/></Button></div>{children}</dialog>
}
function exportRecord(payment: PaymentRequest, versions: History[], books: Books, statements: BankStatement[]) {
  const blob = new Blob([JSON.stringify({ payment, history: versions, currentClearance: paymentClearance(payment, books, statements), exportedAt: new Date().toISOString() }, null, 2)], { type: 'application/json' }), url = URL.createObjectURL(blob), anchor = document.createElement('a')
  anchor.href = url; anchor.download = `supplier-payment-${payment.reference.replace(/[^a-zA-Z0-9_-]/g, '-')}.json`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000)
}
export function PaymentWorkspace() {
  const company = useCompany(), membership = company?.membership, allowed = Boolean(membership?.active && membership.role !== 'viewer')
  const requests = useCompanyRecords<PaymentRequest>('paymentRequests', allowed), accounts = useCompanyRecords<BankAccountRecord>('bankAccounts', allowed), statements = useCompanyRecords<BankStatement>('bankStatements', allowed), versions = useCompanyRecords<History>('paymentRequestVersions', allowed)
  const [filter, setFilter] = useState('active'), [search, setSearch] = useState(''), [selectedId, setSelectedId] = useState(''), [creating, setCreating] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('')
  useEffect(() => { setSelectedId(''); setCreating(false); setError(''); setNotice('') }, [membership?.companyId, membership?.uid, membership?.role])
  async function send(request: CompanyPaymentRequest, message: string) {
    if (!company?.booksReady || !allowed) throw Error('Wait for the company books and your access to finish loading.')
    const result = await company.invoke('companyPayments', { ...request }); setNotice(message); setError(''); return result
  }
  if (!company || !allowed) return <section className={panel}><ShieldCheck className="size-8 text-primary"/><h2 className="mt-4 text-lg font-semibold">Private supplier payment workflow</h2><p className="mt-2 text-sm text-muted-foreground">Company Admins, Accounting Managers and Accountants can prepare and review supplier payment records. Viewers cannot access payment requests or bank reconciliation records.</p></section>
  if (requests.loading || accounts.loading || statements.loading || versions.loading || !company.booksReady) return <p role="status" className={panel}>Loading supplier payments and bank clearance records…</p>
  const loadError = requests.error || accounts.error || statements.error || versions.error
  if (loadError) return <p role="alert" className={panel}>{loadError}</p>
  const sorted = [...requests.rows].sort((a, b) => b.createdAt.localeCompare(a.createdAt)), selected = requests.rows.find(row => row.id === selectedId)
  const shown = sorted.filter(row => (filter === 'all' || filter === 'active' ? filter === 'all' || ['pending', 'approved'].includes(row.status) : row.status === filter) && `${row.reference} ${row.payee} ${row.invoiceReference} ${row.checkNumber}`.toLowerCase().includes(search.toLowerCase()))
  const outstandingBank = requests.rows.filter(row => row.status === 'released').reduce((total, row) => total + paymentClearance(row, company.books, statements.rows).outstandingAmount, 0)
  return <div className="space-y-5"><div className="rounded-xl border border-primary/15 bg-accent/50 p-5"><div className="flex gap-3"><Banknote className="mt-0.5 size-6 shrink-0 text-primary"/><div><h2 className="font-semibold">Prepare → approve → release → clear</h2><p className="mt-1 max-w-4xl text-sm leading-6 text-muted-foreground">Prepare a payment against a supplier bill. A different Admin or Manager approves it. Record the completed transfer or actual check release separately, with supporting evidence. Only release settles the bill and posts cash; bank reconciliation then tracks clearance.</p></div></div></div>
    {notice&&<p role="status" className="rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">{notice}</p>}{error&&<p role="alert" className="rounded-lg bg-red-50 p-4 text-sm text-red-800">{error}</p>}
    <div className="grid gap-3 sm:grid-cols-3">{[['Awaiting approval', requests.rows.filter(row => row.status === 'pending').reduce((total,row)=>total+row.amount,0)], ['Approved for release', requests.rows.filter(row => row.status === 'approved').reduce((total,row)=>total+row.amount,0)], ['Released · not yet bank-cleared', outstandingBank]].map(([label,value])=><div key={String(label)} className={panel}><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold tabular-nums">{money(value as number)}</p></div>)}</div>
    <section className={panel}><div className="flex flex-wrap items-end justify-between gap-3"><div className="flex flex-wrap gap-3"><Field label="Search payments"><input className={input} value={search} placeholder="Supplier, bill, reference or check" onChange={event=>setSearch(event.target.value)}/></Field><Field label="Status"><select className={input} value={filter} onChange={event=>setFilter(event.target.value)}><option value="active">Awaiting approval or release</option><option value="all">All payments</option>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field></div><Button disabled={busy} onClick={()=>setCreating(true)}><Plus size={16}/>Prepare supplier payment</Button></div>
      {!accounts.rows.some(row=>row.active)&&<p className="mt-4 text-sm text-amber-800">Configure an active company bank account in <Link className="underline" to="/accounting/bank-reconciliation">Bank Reconciliation</Link> before preparing payments.</p>}
      <div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-xs text-muted-foreground"><tr>{['Supplier / bill','Request','Amount','Status','Bank clearance',''].map(label=><th key={label} className="px-3 py-3">{label}</th>)}</tr></thead><tbody className="divide-y">{shown.map(row=>{const clearance=paymentClearance(row,company.books,statements.rows);return <tr key={row.id}><td className="px-3 py-4 font-medium">{row.payee}<p className="mt-1 text-xs font-normal text-muted-foreground">{row.invoiceReference}</p></td><td className="px-3 py-4">{row.reference}<p className="mt-1 text-xs text-muted-foreground">{row.method==='check'?`Check ${row.checkNumber}`:'Bank transfer'} · planned {row.plannedDate}</p></td><td className="whitespace-nowrap px-3 py-4 tabular-nums">{money(row.amount)}</td><td className="px-3 py-4"><span className={`rounded-md px-2 py-1 text-xs ${row.status==='released'?'bg-emerald-50 text-emerald-800':row.status==='approved'?'bg-blue-50 text-blue-800':'bg-muted'}`}>{statusLabels[row.status]}</span></td><td className="px-3 py-4 text-xs">{clearanceLabels[clearance.state]}</td><td className="px-3 py-4"><Button size="sm" variant="outline" onClick={()=>setSelectedId(row.id)}>Review payment</Button></td></tr>})}</tbody></table></div>{!shown.length&&<p className="py-9 text-center text-sm text-muted-foreground">No payments match this view. Prepare a request from an unpaid supplier bill to start.</p>}
    </section>
    {creating&&<Modal title="Prepare supplier payment" busy={busy} close={()=>setCreating(false)}><PreparePayment books={company.books} payments={requests.rows} accounts={accounts.rows} busy={busy} setBusy={setBusy} send={send} done={id=>{setCreating(false);setSelectedId(id)}}/></Modal>}
    {selected&&<Modal title={`Supplier payment · ${selected.reference}`} busy={busy} close={()=>setSelectedId('')}><PaymentDetail key={selected.id} payment={selected} versions={versions.rows.filter(row=>row.requestId===selected.id).sort((a,b)=>b.version-a.version)} books={company.books} statements={statements.rows} busy={busy} setBusy={setBusy} send={send}/></Modal>}
  </div>
}

function PreparePayment({books,payments,accounts,busy,setBusy,send,done}:{books:Books;payments:PaymentRequest[];accounts:BankAccountRecord[];busy:boolean;setBusy:(value:boolean)=>void;send:Send;done:(id:string)=>void}) {
  const company=useCompany()!,preview=useContext(CompanyRecordsPreview),requestId=useRef(crypto.randomUUID()),mounted=useMounted()
  const [invoiceId,setInvoiceId]=useState(''),[bankId,setBankId]=useState(''),[amount,setAmount]=useState(''),[plannedDate,setPlannedDate]=useState(today()),[method,setMethod]=useState<PaymentMethod|''>(''),[checkNumber,setCheckNumber]=useState(''),[reference,setReference]=useState(''),[notes,setNotes]=useState(''),[confirmed,setConfirmed]=useState(false),[documents,setDocuments]=useState<PendingSettlementEvidence[]>([]),[validating,setValidating]=useState(false),[error,setError]=useState('')
  const reserved=(id:string)=>payments.filter(row=>row.invoiceId===id&&['pending','approved'].includes(row.status)&&row.id!==requestId.current).reduce((sum,row)=>sum+row.amount,0)
  const bills=books.invoices.filter(row=>row.kind==='payable'&&outstanding(books,row)>0),bill=bills.find(row=>row.id===invoiceId),bank=accounts.find(row=>row.id===bankId&&row.active)
  async function submit(event:FormEvent){event.preventDefault();if(busy||validating)return;setError('');setBusy(true);try{
    if(!bill||!bank||!method)throw Error('Choose the supplier bill, active bank account and payment method.')
    const value=cents(amount),available=outstanding(books,bill)-reserved(bill.id)
    if(value<=0||value>available)throw Error('The amount exceeds the unreserved outstanding bill balance. Refresh the bill and existing payment requests.')
    if(!validBankDate(plannedDate)||plannedDate<bill.date)throw Error('Choose a planned date on or after the bill date.')
    if(!reference.trim()||notes.trim().length<10||!confirmed)throw Error('Add the request reference and purpose, then confirm the payment details.')
    const cleanCheck=checkNumber.toUpperCase().replace(/\s+/g,'');if(method==='check'&&!/^[A-Z0-9-]{1,40}$/.test(cleanCheck))throw Error('Enter a check number of at most 40 letters, numbers or hyphens.')
    if(documents.length===10&&!documents.some(row=>row.kind===(method==='check'?'check_copy':'transfer_confirmation')))throw Error('Leave at least one attachment slot for the required release evidence, or include that evidence now.')
    const supportingDocuments=await saveSettlementEvidence(documents,company.membership!.companyId,!!preview)
    const payload:PaymentRequestInput={invoiceId,bankId,amount:value,plannedDate,method,checkNumber:method==='check'?cleanCheck:'',reference:reference.trim(),notes:notes.trim(),supportingDocuments}
    if(!mounted.current)return
    const result=await send({action:'prepare',requestId:requestId.current,input:payload},'Payment prepared for independent approval. No cash or supplier balance has changed.');done(String(result.id||requestId.current))
  }catch(cause){setError(cause instanceof Error?cause.message:'The payment could not be prepared.')}finally{setBusy(false)}}
  return <form onSubmit={submit} className="space-y-5"><p className="text-sm leading-6 text-muted-foreground">This request reserves an amount for review. It does not transfer funds, issue a check, or record a payment. Cancel and prepare a replacement if the approved details later need changing.</p><fieldset disabled={busy} className="grid gap-4 sm:grid-cols-2"><Field label="Unpaid supplier bill"><select className={input} required value={invoiceId} onChange={event=>{setInvoiceId(event.target.value);setAmount('');setConfirmed(false)}}><option value="">Choose a posted supplier bill</option>{bills.map(row=><option key={row.id} value={row.id}>{row.party} · {row.reference} · available {money(Math.max(0,outstanding(books,row)-reserved(row.id)))}</option>)}</select></Field><Field label="Company bank account"><select required className={input} value={bankId} onChange={event=>{setBankId(event.target.value);setConfirmed(false)}}><option value="">Choose active bank account</option>{accounts.filter(row=>row.active).map(row=><option key={row.id} value={row.id}>{row.name} · {row.bankName} · …{row.accountSuffix}</option>)}</select></Field><Field label="Payment amount (PHP)"><input className={input} required inputMode="decimal" value={amount} onChange={event=>{setAmount(event.target.value);setConfirmed(false)}}/></Field><Field label="Planned payment date"><input className={input} type="date" required min={bill?.date} value={plannedDate} onChange={event=>{setPlannedDate(event.target.value);setConfirmed(false)}}/></Field><Field label="Payment method"><select required className={input} value={method} onChange={event=>{setMethod(event.target.value as PaymentMethod);setConfirmed(false)}}><option value="">Choose method</option><option value="transfer">Bank transfer</option><option value="check">Check</option></select></Field><Field label="Request reference"><input className={input} required maxLength={150} value={reference} onChange={event=>{setReference(event.target.value);setConfirmed(false)}}/></Field>{method==='check'&&<Field label="Check number"><input className={input} required maxLength={40} value={checkNumber} onChange={event=>{setCheckNumber(event.target.value);setConfirmed(false)}}/></Field>}</fieldset>
    {bill&&<div className="rounded-lg bg-muted/40 p-4 text-sm"><p className="font-semibold">{bill.party} · {bill.reference}</p><p className="mt-1">Outstanding {money(outstanding(books,bill))} · reserved in other requests {money(reserved(bill.id))}</p><SupplierBillPdfLink file={bill.supplierBillPdf}/></div>}
    <Field label="Payment purpose and review notes"><textarea className={input} disabled={busy} required minLength={10} maxLength={2000} rows={3} value={notes} onChange={event=>{setNotes(event.target.value);setConfirmed(false)}}/></Field><SettlementEvidence value={documents} onChange={setDocuments} invoiceKind="payable" disabled={busy} onValidating={setValidating}/><label className="flex gap-2 text-sm leading-6"><input type="checkbox" disabled={busy} checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/><span>I reviewed the supplier, bill, bank, amount and payment method. A different Admin or Manager must approve this request.</span></label>{error&&<p role="alert" className="rounded-md bg-red-50 p-3 text-sm text-red-800">{error}</p>}<Button type="submit" disabled={busy||validating||!confirmed||!bill||!bank||!method}><ClipboardCheck size={16}/>{busy?'Saving request…':'Submit for payment approval'}</Button></form>
}

type Action='approve'|'reject'|'cancel'|'release'|'attachDocuments'
function PaymentDetail({payment,versions,books,statements,busy,setBusy,send}:{payment:PaymentRequest;versions:History[];books:Books;statements:BankStatement[];busy:boolean;setBusy:(value:boolean)=>void;send:Send}) {
  const company=useCompany()!,member=company.membership!,canManage=['admin','manager'].includes(member.role),own=payment.createdBy===member.uid
  const [action,setAction]=useState<Action|null>(null),clearance=paymentClearance(payment,books,statements),bill=books.invoices.find(row=>row.id===payment.invoiceId)
  const canCancel=payment.status==='pending'&&(own||canManage)||payment.status==='approved'&&canManage,canAttach=payment.supportingDocuments.length<10&&(['pending','approved','released'].includes(payment.status)&&canManage||payment.status==='pending'&&own)
  return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3">{[['Supplier',payment.payee],['Supplier bill',payment.invoiceReference],['Amount',money(payment.amount)],['Bank account',`${payment.bankName} · …${payment.accountSuffix}`],['Method',payment.method==='check'?`Check ${payment.checkNumber}`:'Bank transfer'],['Status',statusLabels[payment.status]]].map(([label,value])=><div key={label} className="rounded-lg bg-muted/40 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 break-words text-sm font-semibold">{value}</p></div>)}</div>
    <p className="text-sm leading-6">{payment.notes}</p><div className="grid gap-3 text-xs leading-5 text-muted-foreground sm:grid-cols-2"><p>Prepared {payment.createdAt.slice(0,10)} by {payment.createdBy}<br/>Planned payment {payment.plannedDate} · version {payment.version}</p><p>{payment.approvedAt?`Approved ${payment.approvedAt.slice(0,10)} by ${payment.approvedBy}`:'Independent approval pending'}{payment.releaseDate&&<><br/>Released {payment.releaseDate} by {payment.releasedBy}<br/>Confirmation {payment.confirmationReference}</>}</p></div>
    {payment.reviewNote&&<p className="rounded-lg border p-3 text-sm">Latest action note: {payment.reviewNote}</p>}{bill&&<div className="rounded-lg border p-4 text-sm"><Link className="text-primary underline" to={`/accounting/payable?q=${encodeURIComponent(payment.invoiceReference)}`}>Open source bill</Link><span className="ml-3 text-muted-foreground">Current outstanding {money(outstanding(books,bill))}{isReversed(books,bill.entryId)?' · Bill reversed':''}</span><SupplierBillPdfLink file={bill.supplierBillPdf}/></div>}
    <section className="rounded-lg border p-4"><h3 className="text-sm font-semibold">Saved payment evidence ({payment.supportingDocuments.length}/10)</h3><SettlementEvidenceList files={payment.supportingDocuments}/>{!payment.supportingDocuments.length&&<p className="mt-2 text-sm text-muted-foreground">No documents attached yet. Proof of the completed transfer or released check is required before recording release.</p>}</section>
    {payment.status==='released'&&<section className="rounded-lg border border-primary/20 bg-accent/30 p-4"><h3 className="flex items-center gap-2 font-semibold"><CheckCircle2 size={18}/>{clearanceLabels[clearance.state]}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Clearance comes from current approved bank reconciliations. Reopening one changes this status without posting cash again.</p><div className="my-3 flex flex-wrap gap-5 text-sm"><span>Released <b>{money(clearance.releasedAmount)}</b></span><span>Cleared <b>{money(clearance.clearedAmount)}</b></span><span>Outstanding <b>{money(clearance.outstandingAmount)}</b></span></div>{clearance.links.map((link,index)=><p key={`${link.statementId}-${link.bankRowId}-${index}`} className="mt-1 text-xs">{link.date} · {link.reference} v{link.version} · {money(link.amount)}</p>)}<div className="mt-3 flex flex-wrap gap-4 text-sm"><Link className="text-primary underline" to="/accounting/bank-reconciliation">Open bank reconciliation</Link>{payment.entryId&&<Link className="text-primary underline" to={`/accounting/journal?q=${encodeURIComponent(payment.reference)}`}>View payment journal</Link>}</div></section>}
    {!action&&<div className="space-y-3"><div className="flex flex-wrap gap-2">{payment.status==='pending'&&canManage&&<><Button disabled={busy||own} onClick={()=>setAction('approve')}><ClipboardCheck size={16}/>Approve for release</Button><Button disabled={busy} variant="outline" onClick={()=>setAction('reject')}>Reject request</Button></>}{payment.status==='approved'&&canManage&&<Button disabled={busy} onClick={()=>setAction('release')}><FileCheck2 size={16}/>Record actual release</Button>}{canCancel&&<Button disabled={busy} variant="outline" onClick={()=>setAction('cancel')}>Cancel request</Button>}{canAttach&&<Button disabled={busy} variant="outline" onClick={()=>setAction('attachDocuments')}>Add documents</Button>}<Button disabled={busy} variant="outline" onClick={()=>exportRecord(payment,versions,books,statements)}><Download size={16}/>Export payment record</Button></div>{payment.status==='pending'&&own&&<p className="text-xs text-amber-800">You prepared this request. Another Admin or Manager must approve it.</p>}{payment.status==='approved'&&<p className="text-sm text-muted-foreground">Approval has not reduced cash or the supplier balance. Record release only after the transfer completes or the check is actually released to the payee.</p>}</div>}
    {action&&<PaymentAction key={`${payment.id}-${action}`} action={action} payment={payment} books={books} busy={busy} setBusy={setBusy} send={send} done={()=>setAction(null)}/>}
    <details className="rounded-lg border p-4"><summary className="cursor-pointer text-sm font-semibold">Immutable request history ({versions.length})</summary><p className="mt-2 text-xs text-muted-foreground">Each saved action keeps its previous information. An approved or released request is corrected through the controlled actions, preserving earlier versions.</p><div className="mt-3 space-y-3">{versions.map(row=><article key={`${row.requestId}-${row.version}`} className="rounded-lg bg-muted/40 p-3 text-xs"><b>Version {row.version} · {row.changeAction} · {statusLabels[row.status]}</b><p className="mt-1">{row.updatedAt} · {row.updatedBy} · {money(row.amount)}</p><p className="mt-1">{row.reviewNote||row.notes}</p><SettlementEvidenceList files={row.supportingDocuments}/></article>)}{!versions.length&&<p className="text-sm text-muted-foreground">Saved action versions will appear here.</p>}</div></details>
  </div>
}

function PaymentAction({action,payment,books,busy,setBusy,send,done}:{action:Action;payment:PaymentRequest;books:Books;busy:boolean;setBusy:(value:boolean)=>void;send:Send;done:()=>void}) {
  const company=useCompany()!,preview=useContext(CompanyRecordsPreview),mounted=useMounted(),[version]=useState(payment.version),[booksRevision]=useState(company.revision),[note,setNote]=useState(''),[releaseDate,setReleaseDate]=useState(today()),[confirmationReference,setConfirmationReference]=useState(''),[confirmed,setConfirmed]=useState(false),[documents,setDocuments]=useState<PendingSettlementEvidence[]>([]),[validating,setValidating]=useState(false),[error,setError]=useState('')
  const stale=payment.version!==version||(action==='release'&&company.revision!==booksRevision),requiredKind=payment.method==='check'?'check_copy':'transfer_confirmation',hasEvidence=[...payment.supportingDocuments,...documents].some(row=>row.kind===requiredKind)
  const label={approve:'Approve for release',reject:'Reject payment request',cancel:'Cancel payment request',release:'Record actual payment release',attachDocuments:'Add supporting documents'}[action]
  async function submit(event:FormEvent){event.preventDefault();if(busy||validating)return;setError('');setBusy(true);try{
    if(stale)throw Error('The request or books changed. Return to payment details and reopen this action.')
    if(note.trim().length<10)throw Error('Add a note of at least 10 characters explaining your action and review.')
    let request:CompanyPaymentRequest
    if(action==='release'){
      const bill=books.invoices.find(row=>row.id===payment.invoiceId)
      if(!bill||outstanding(books,bill)<payment.amount)throw Error('The source bill no longer has this outstanding amount. Cancel this request and review the bill.')
      if(!confirmed||!hasEvidence)throw Error(`Confirm the actual ${payment.method==='check'?'check release':'completed transfer'} and attach ${payment.method==='check'?'a check copy':'the transfer confirmation'}.`)
      if(!validBankDate(releaseDate)||releaseDate>today()||releaseDate<bill.date||releaseDate<=books.closedThrough)throw Error('Choose an actual release date in an open period, on or after the bill date and no later than today.')
      if(!confirmationReference.trim())throw Error('Enter the actual bank confirmation or check release reference.')
      const supportingDocuments=await saveSettlementEvidence(documents,company.membership!.companyId,!!preview)
      request={action,id:payment.id,expectedVersion:version,expectedBooksRevision:booksRevision,releaseDate,confirmation:payment.method==='check'?'check_released':'transfer_completed',confirmationReference:confirmationReference.trim(),supportingDocuments,note:note.trim()}
    }else if(action==='attachDocuments'){
      if(!documents.length)throw Error('Choose at least one new supporting document.')
      if(payment.status!=='released'&&payment.supportingDocuments.length+documents.length===10&&!hasEvidence)throw Error('Leave an attachment slot for the required release evidence before filling all 10 slots.')
      request={action,id:payment.id,expectedVersion:version,supportingDocuments:await saveSettlementEvidence(documents,company.membership!.companyId,!!preview),note:note.trim()}
    }else{if(action==='approve'&&!confirmed)throw Error('Confirm your independent review before approving.');request={action,id:payment.id,expectedVersion:version,note:note.trim()}}
    if(!mounted.current)return
    await send(request,action==='release'?'Payment released and posted once to the supplier balance and cash ledger. Bank clearance remains a separate step.':action==='approve'?'Payment approved for release. Cash and the supplier balance are unchanged.':action==='attachDocuments'?'Supporting documents appended to the payment record.':`Payment request ${action==='cancel'?'cancelled':'rejected'}. No cash was posted.`);done()
  }catch(cause){setError(cause instanceof Error?cause.message:'The payment action could not be completed.')}finally{setBusy(false)}}
  return <form onSubmit={submit} className="space-y-4 rounded-xl border border-primary/25 bg-accent/20 p-4"><h3 className="font-semibold">{label}</h3>{action==='release'&&<><p className="text-sm leading-6 text-muted-foreground">This records an action completed outside TaxPhil. It settles {money(payment.amount)} against the bill and credits bank account {payment.cashAccount}. {payment.method==='check'?'Preparing or signing a check is not its release.':'An approved transfer request is not proof that the bank completed it.'}</p><fieldset disabled={busy} className="grid gap-4 sm:grid-cols-2"><Field label="Actual release date"><input required type="date" max={today()} value={releaseDate} onChange={event=>{setReleaseDate(event.target.value);setConfirmed(false)}} className={input}/></Field><Field label={payment.method==='check'?'Check release / acknowledgment reference':'Actual bank transfer confirmation reference'}><input required className={input} maxLength={150} value={confirmationReference} onChange={event=>{setConfirmationReference(event.target.value);setConfirmed(false)}}/></Field></fieldset></>}
    {(action==='release'||action==='attachDocuments')&&<><SettlementEvidence value={documents} onChange={setDocuments} invoiceKind="payable" existingCount={payment.supportingDocuments.length} disabled={busy} onValidating={setValidating}/>{action==='release'&&<p className={`text-xs ${hasEvidence?'text-emerald-800':'text-amber-800'}`}>{hasEvidence?'Required evidence is attached.':`Required: ${payment.method==='check'?'check copy':'transfer confirmation'}.`} Maximum 10 documents across the request and release. A vendor receipt can be appended later.</p>}</>}
    <Field label={action==='release'?'Release note: completion and delivery to the payee':'Action and review note'}><textarea className={input} required minLength={10} maxLength={2000} rows={3} disabled={busy} value={note} onChange={event=>setNote(event.target.value)}/></Field>
    {(action==='release'||action==='approve')&&<label className="flex gap-2 text-sm leading-6"><input type="checkbox" checked={confirmed} disabled={busy} onChange={event=>setConfirmed(event.target.checked)}/><span>{action==='approve'?'I independently reviewed the supplier bill, amount, bank, method and evidence. This authorizes release and does not record a cash payment.':payment.method==='check'?'I confirm that this check was actually released to the named payee on the recorded date. The check image and release note support that event.':'I confirm that the bank transfer completed for the named payee on the recorded date, supported by the transfer confirmation.'}</span></label>}
    {stale&&<p role="alert" className="text-sm text-amber-800">This request or the company books changed. Return to payment details and reopen the action before proceeding.</p>}{error&&<p role="alert" className="rounded-md bg-red-50 p-3 text-sm text-red-800">{error}</p>}<div className="flex flex-wrap gap-2"><Button type="submit" disabled={busy||validating||stale||note.trim().length<10||((action==='approve'||action==='release')&&!confirmed)||(action==='release'&&!hasEvidence)||(action==='attachDocuments'&&!documents.length)}>{busy?'Saving…':label}</Button><Button type="button" variant="outline" disabled={busy} onClick={done}>Back to payment details</Button></div></form>
}
