import { useContext, useEffect, useState, type FormEvent } from 'react'
import { collection, doc, onSnapshot, orderBy, query } from 'firebase/firestore'
import { Link } from 'react-router-dom'
import { ExternalLink, FileText, Plus, Printer, Search, ShieldCheck, Users, X } from 'lucide-react'
import { db } from '@/lib/firebase'
import { useCompany } from '@/hooks/useCompany'
import { CompanyRecordsPreview } from '@/hooks/useCompanyRecords'
import { money, today } from '@/lib/accounting'
import { applyMonthlyPayrollSuggestion, applyPayrollWithholdingSuggestion, payrollFullContributionMonth, payrollAmountFields, blankPayrollRow, calculatePayrollRun, emptyPayrollAccounts, payrollAccountLabels, payrollDeductions, payrollEarnings, payrollEmployerCosts, payrollFieldLabels, payrollSources, validateEmployee, type EmployeeRecord, type PayrollAccounts, type PayrollAmountField, type PayrollRow, type PayrollRowInput, type PayrollRun, type PayrollRunInput, type PayrollPeriodContext, type PayrollStatutoryEvidence } from '@/lib/payroll'

import { payrollStatutoryVerifiedOn, suggestMonthlyContributions, suggestCompensationWithholding, type MonthlyContributionSuggestion, type CompensationWithholdingSuggestion } from '@/lib/payroll-statutory'

interface SavedRun extends PayrollRun { id: string; version: number; status: 'draft' | 'posted'; createdBy: string; createdByEmail: string; companyName: string; approvedBy?: string; reviewNote?: string; entryId?: string }
const inputClass = 'h-10 w-full rounded-md border border-slate-200 bg-white px-3 text-sm text-slate-900'
const primary = 'inline-flex items-center justify-center gap-2 rounded-lg bg-blue-700 px-4 py-2.5 text-sm font-medium text-white hover:bg-blue-800 disabled:opacity-50'
const secondary = 'inline-flex items-center justify-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-medium text-slate-600 hover:bg-slate-50 disabled:opacity-50'
const frequencyLabels = { monthly: 'Monthly', semi_monthly: 'Semi-monthly', weekly: 'Weekly', daily: 'Daily' }
function amount(value: string) { if (!/^\d+(\.\d{0,2})?$/.test(value)) throw Error('Enter an amount with at most two decimal places.'); const result = Math.round(Number(value) * 100); if (!Number.isSafeInteger(result)) throw Error('Invalid amount.'); return result }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block space-y-2 text-sm font-medium text-slate-600"><span>{label}</span>{children}</label> }
function GovernmentReferences() { return <div className="rounded-xl border border-blue-100 bg-blue-50 p-5"><p className="text-sm font-semibold text-blue-900">Philippine payroll reference desk</p><p className="mt-2 text-sm leading-7 text-slate-600">Enter reviewed contribution and tax amounts for this payroll period. The optional calculator previews verified contribution tables and ordinary withholding from reviewed bases. Exemptions, minimum wages, overtime rules, annualization, and cut-off allocations require separate review. Record your basis and adjustments before approval.</p><div className="mt-4 flex flex-wrap gap-4">{payrollSources.map(source => <a key={source.agency} href={source.url} target="_blank" rel="noopener noreferrer" title={source.title} className="inline-flex items-center gap-1.5 text-sm font-semibold text-blue-700">{source.agency}<ExternalLink className="size-3.5" /></a>)}</div></div> }

export function PayrollWorkspace({ section }: { section: 'employees' | 'payroll' }) {
  const preview=useContext(CompanyRecordsPreview)
  const company = useCompany(), member = company?.membership
  const allowed = Boolean(member?.active && member.role !== 'viewer'), scope = allowed ? `${member!.companyId}:${member!.role}:${member!.uid}` : ''
  const [state, setState] = useState<{ scope: string; employees: EmployeeRecord[]; revision: number; runs: SavedRun[]; employeesReady: boolean; runsReady: boolean; error: string }>({ scope: '', employees: [], revision: 0, runs: [], employeesReady: false, runsReady: false, error: '' })
  const [busy, setBusy] = useState(false), [notice, setNotice] = useState(''), [actionError, setActionError] = useState('')
  useEffect(() => {
    let cancelled = false
    setState({ scope, employees: [], revision: 0, runs: [], employeesReady: false, runsReady: false, error: '' }); setNotice(''); setActionError('')
    if (!scope || !member?.companyId) return
    if(preview){const employees=(preview.employees?.[0]||{employees:[],revision:0}) as {employees:EmployeeRecord[];revision:number};setState({scope,employees:employees.employees,revision:employees.revision,runs:(preview.payrollRuns||[]) as SavedRun[],employeesReady:true,runsReady:true,error:''});return}
    const fail = (reason: Error) => { if (!cancelled) setState(old => ({ ...old, error: `Payroll records could not be loaded: ${reason.message}` })) }
    const stopEmployees = onSnapshot(doc(db, 'companies', member.companyId, 'employees', 'default'), snapshot => { if (!cancelled) setState(old => ({ ...old, employees: snapshot.data()?.employees || [], revision: snapshot.data()?.revision || 0, employeesReady: true })) }, fail)
    const stopRuns = onSnapshot(query(collection(db, 'companies', member.companyId, 'payrollRuns'), orderBy('createdAt', 'desc')), snapshot => { if (!cancelled) setState(old => ({ ...old, runs: snapshot.docs.map(row => ({ ...row.data(), id: row.id } as SavedRun)), runsReady: true })) }, fail)
    return () => { cancelled = true; stopEmployees(); stopRuns() }
  }, [scope, member?.companyId, preview])
  async function command(data: Record<string, unknown>, success: string) {
    if (!company || !allowed || busy) return false
    setBusy(true); setNotice(''); setActionError('')
    try { await company.invoke('companyPayroll', data); setNotice(success); return true }
    catch (reason) { setActionError(reason instanceof Error ? reason.message : 'The payroll action failed.'); return false }
    finally { setBusy(false) }
  }
  if (!allowed) return <div className="rounded-xl border border-slate-200 bg-white p-8"><ShieldCheck className="size-7 text-blue-700" /><h2 className="mt-4 text-xl font-semibold">Employee and payroll access</h2><p className="mt-3 text-sm leading-7 text-slate-600">Private employee and salary records are available to active Company Admins, Accounting Managers, and Accountants.</p></div>
  if (state.scope !== scope || (!state.error && (!state.employeesReady || !state.runsReady))) return <p role="status" className="p-6 text-sm text-slate-500">Loading private employee and payroll records…</p>
  if (state.error) return <p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-5 text-sm text-red-800">{state.error}</p>
  return <div className="space-y-6">{notice && <p role="status" className="rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">{notice}</p>}{actionError && <p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800">{actionError}</p>}
    <div className="flex flex-wrap gap-3"><Link className={section === 'employees' ? primary : secondary} to="/accounting/employees"><Users className="size-4" />Employees</Link><Link className={section === 'payroll' ? primary : secondary} to="/accounting/payroll"><FileText className="size-4" />Payroll</Link></div>
    {section === 'employees' ? <Employees key={scope} employees={state.employees} revision={state.revision} busy={busy} command={command} /> : <PayrollRuns key={scope} employees={state.employees} employeeRevision={state.revision} runs={state.runs} busy={busy} command={command} />}
    <GovernmentReferences />
  </div>
}
type Command = (data: Record<string, unknown>, success: string) => Promise<boolean>
function Employees({ employees, revision, busy, command }: { employees: EmployeeRecord[]; revision: number; busy: boolean; command: Command }) {
  const [queryText, setQuery] = useState(''), [filter, setFilter] = useState('all'), [editing, setEditing] = useState<EmployeeRecord | 'new' | null>(null)
  const filtered = employees.filter(employee => (filter === 'all' || (filter === 'active') === employee.active) && `${employee.code} ${employee.fullName} ${employee.department}`.toLowerCase().includes(queryText.toLowerCase()))
  return <div className="space-y-5"><div className="flex flex-col gap-4 rounded-xl border border-slate-200 bg-white p-6 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-semibold">Your employee register</h2><p className="mt-2 text-sm text-slate-500">{employees.filter(row => row.active).length} active · {employees.length} total · Private company records</p></div><button className={primary} onClick={() => setEditing('new')} disabled={busy}><Plus className="size-4" />Add employee</button></div>
    {editing && <EmployeeEditor key={editing === 'new' ? 'new' : editing.id} employee={editing === 'new' ? null : editing} revision={revision} busy={busy} command={command} close={() => setEditing(null)} />}
    <div className="flex gap-3"><label className="relative flex-1"><Search className="absolute top-3 left-3 size-4 text-slate-400" /><span className="sr-only">Search employees</span><input className={`${inputClass} pl-9`} placeholder="Search name, code, or department" value={queryText} onChange={e => setQuery(e.target.value)} /></label><select aria-label="Employee status filter" className={`${inputClass} max-w-36`} value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All employees</option><option value="active">Active</option><option value="inactive">Inactive</option></select></div>
    <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr>{['Employee', 'Department', 'Basic pay per period', 'Status', 'Registration', ''].map((label, index) => <th key={index} className="px-5 py-4 font-medium">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(employee => <tr key={employee.id}><td className="px-5 py-4"><p className="font-semibold text-slate-900">{employee.fullName}</p><p className="mt-1 text-xs text-slate-500">{employee.code} · TIN ending {employee.tin.slice(-4)}</p></td><td className="px-5 py-4">{employee.department || '—'}</td><td className="px-5 py-4"><p>{money(employee.basicPay)}</p><p className="mt-1 text-xs text-slate-500">{frequencyLabels[employee.payFrequency]}</p></td><td className="px-5 py-4">{employee.active ? 'Active' : 'Inactive'}</td><td className="px-5 py-4 text-xs text-slate-500">{[!employee.sssNumber && 'SSS', !employee.philhealthNumber && 'PhilHealth', !employee.pagibigNumber && 'Pag-IBIG'].filter(Boolean).join(', ') || 'IDs recorded'}{(!employee.sssNumber || !employee.philhealthNumber || !employee.pagibigNumber) && ' ID missing'}</td><td className="px-5 py-4"><button className="font-semibold text-blue-700" onClick={() => setEditing(employee)}>Edit</button></td></tr>)}</tbody></table>{filtered.length === 0 && <p className="p-8 text-center text-sm text-slate-500">{employees.length ? 'No employees match your filters.' : 'Add your first employee to prepare payroll.'}</p>}</div>
  </div>
}
function EmployeeEditor({ employee, revision, busy, command, close }: { employee: EmployeeRecord | null; revision: number; busy: boolean; command: Command; close: () => void }) {
  const [initialRevision] = useState(revision)
  const [form, setForm] = useState(employee || { id: '', version: 0, code: '', fullName: '', tin: '', sssNumber: '', philhealthNumber: '', pagibigNumber: '', address: '', compensationAtc: '', department: '', jobTitle: '', startDate: today(), endDate: '', active: true, payFrequency: 'monthly' as const, basicPay: 0, notes: '' })
  const [pay, setPay] = useState(employee ? (employee.basicPay / 100).toFixed(2) : ''), [error, setError] = useState('')
  const field = (key: keyof EmployeeRecord, value: unknown) => setForm(old => ({ ...old, [key]: value }))
  async function save(event: FormEvent) { event.preventDefault(); setError(''); try { const value = { ...form, basicPay: amount(pay) }; validateEmployee(value, employee?.id || 'new-employee', 1); if (await command({ action: 'saveEmployee', employeeId: employee?.id, input: value, expectedRevision: initialRevision }, 'Employee record saved. Existing payroll drafts must be reviewed again.')) close() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Check employee details.') } }
  return <form onSubmit={save} className="rounded-xl border border-blue-200 bg-white p-6"><div className="flex items-center justify-between"><h3 className="text-lg font-semibold">{employee ? `Edit ${employee.code}` : 'New employee'}</h3><button type="button" onClick={close} aria-label="Close employee editor"><X className="size-5" /></button></div>{error && <p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}{revision !== initialRevision && <p role="alert" className="mt-4 text-sm text-amber-800">Employee records changed while editing. Close and reopen this form to load the current revision.</p>}
    <div className="mt-5 grid gap-4 md:grid-cols-2">{(['code', 'fullName', 'tin', 'compensationAtc', 'sssNumber', 'philhealthNumber', 'pagibigNumber', 'department', 'jobTitle'] as const).map(key => <Field key={key} label={{ code: 'Employee code', fullName: 'Registered full name', tin: 'TIN (9 digits, required)', compensationAtc: 'Reviewed compensation ATC', sssNumber: 'SSS number (optional)', philhealthNumber: 'PhilHealth number (optional)', pagibigNumber: 'Pag-IBIG MID (optional)', department: 'Department', jobTitle: 'Job title' }[key]}><input className={inputClass} value={form[key]} required={['code', 'fullName', 'tin', 'compensationAtc'].includes(key)} maxLength={key === 'fullName' ? 150 : 120} onChange={e => field(key, e.target.value)} /></Field>)}<Field label="Pay frequency"><select className={inputClass} value={form.payFrequency} onChange={e => field('payFrequency', e.target.value)}>{Object.entries(frequencyLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field label="Basic pay per payroll period (PHP)"><input className={inputClass} value={pay} required inputMode="decimal" onChange={e => setPay(e.target.value)} placeholder="0.00" /></Field><Field label="Employment start"><input type="date" className={inputClass} value={form.startDate} required onChange={e => field('startDate', e.target.value)} /></Field><Field label="Employment end (optional)"><input type="date" className={inputClass} value={form.endDate} onChange={e => field('endDate', e.target.value)} /></Field><Field label="Status"><select className={inputClass} value={form.active ? 'active' : 'inactive'} onChange={e => field('active', e.target.value === 'active')}><option value="active">Active</option><option value="inactive">Inactive</option></select></Field></div><div className="mt-4 space-y-4"><Field label="Registered address"><textarea className={`${inputClass} h-20 py-2`} value={form.address} maxLength={500} required onChange={e => field('address', e.target.value)} /></Field><Field label="Notes"><textarea className={`${inputClass} h-20 py-2`} value={form.notes} maxLength={1000} onChange={e => field('notes', e.target.value)} /></Field></div><p className="mt-4 text-xs leading-6 text-slate-500">Basic pay is the amount for one selected payroll period, not a monthly rate to be automatically prorated. Changing employee status retains their payroll history.</p><div className="mt-5 flex gap-3"><button className={primary} disabled={busy || revision !== initialRevision}>{busy ? 'Saving…' : 'Save employee'}</button><button type="button" className={secondary} onClick={close}>Cancel</button></div></form>
}
function PayrollRuns({ employees, employeeRevision, runs, busy, command }: { employees: EmployeeRecord[]; employeeRevision: number; runs: SavedRun[]; busy: boolean; command: Command }) {
  const company = useCompany()!, [editing, setEditing] = useState<SavedRun | 'new' | null>(null), [selectedId, setSelectedId] = useState(''), [queryText, setQuery] = useState(''), [reviewNote, setReviewNote] = useState(''), [printError, setPrintError] = useState('')
  const selected = runs.find(run => run.id === selectedId), filtered = runs.filter(run => `${run.reference} ${run.periodStart} ${run.status}`.toLowerCase().includes(queryText.toLowerCase()))
  const canApprove = company.membership?.role === 'admin' || company.membership?.role === 'manager'
  return <div className="space-y-5"><div className="flex flex-col gap-4 rounded-xl border border-slate-200 bg-white p-6 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-semibold">Prepare, review, and post payroll</h2><p className="mt-2 text-sm text-slate-500">{runs.filter(run => run.status === 'draft').length} drafts · {runs.filter(run => run.status === 'posted').length} posted runs</p></div><button className={primary} onClick={() => setEditing('new')} disabled={busy || !employees.some(row => row.active)}><Plus className="size-4" />Prepare payroll</button></div>
    {employees.length === 0 && <p className="rounded-lg border border-slate-200 bg-white p-5 text-sm text-slate-600">Add employees first, then prepare a payroll run for their pay frequency.</p>}
    {editing && <PayrollEditor key={editing === 'new' ? 'new' : editing.id} run={editing === 'new' ? null : editing} employees={employees} employeeRevision={employeeRevision} runs={runs} busy={busy} command={command} close={() => setEditing(null)} />}
    <label className="relative block"><Search className="absolute top-3 left-3 size-4 text-slate-400" /><span className="sr-only">Search payroll runs</span><input className={`${inputClass} pl-9`} placeholder="Search reference, period, or status" value={queryText} onChange={e => setQuery(e.target.value)} /></label>
    <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr>{['Payroll', 'Period', 'Gross pay', 'Net pay', 'Status', ''].map((label, index) => <th className="px-5 py-4 font-medium" key={index}>{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(run => <tr key={run.id}><td className="px-5 py-4"><p className="font-semibold">{run.reference}</p><p className="mt-1 text-xs text-slate-500">{run.rows.length} employees</p></td><td className="px-5 py-4 text-xs text-slate-500">{run.periodStart}<br />to {run.periodEnd}</td><td className="px-5 py-4 whitespace-nowrap">{money(run.totals.grossPay)}</td><td className="px-5 py-4 whitespace-nowrap">{money(run.totals.netPay)}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${run.status === 'posted' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-800'}`}>{run.status === 'posted' ? 'Posted' : 'Draft'}</span></td><td className="px-5 py-4"><button className="font-semibold text-blue-700" onClick={() => { setSelectedId(run.id); setReviewNote(''); setPrintError('') }}>Review</button></td></tr>)}</tbody></table>{filtered.length === 0 && <p className="p-8 text-center text-sm text-slate-500">No payroll runs match this view.</p>}</div>
    {selected && <section className="rounded-xl border border-blue-200 bg-white p-6"><div className="flex items-start justify-between gap-3"><div><h3 className="text-xl font-semibold">{selected.reference}</h3><p className="mt-2 text-sm text-slate-500">{selected.periodStart} to {selected.periodEnd} · Pay date {selected.payDate} · Prepared by {selected.createdByEmail}</p></div><button aria-label="Close payroll review" onClick={() => setSelectedId('')}><X className="size-5" /></button></div><div className="mt-5 grid gap-3 sm:grid-cols-4">{[['Gross pay', selected.totals.grossPay], ['Employee deductions', selected.totals.deductions], ['Net pay', selected.totals.netPay], ['Employer contributions', selected.totals.employerContributions]].map(([label, value]) => <div key={label as string} className="rounded-lg bg-slate-50 p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 font-semibold">{money(value as number)}</p></div>)}</div><div className="mt-5 rounded-lg border border-slate-200 p-4"><p className="text-sm font-semibold">Calculation review</p><p className="mt-2 text-sm leading-7 whitespace-pre-wrap text-slate-600">{selected.calculationNote || 'The preparer has not recorded calculation notes.'}</p><p className="mt-2 text-xs text-slate-500">{selected.calculationsReviewed ? 'Preparer confirmed calculations reviewed.' : 'Preparer review is outstanding.'}</p></div>
      <div className="mt-5 space-y-3">{selected.rows.map(row => <details key={row.employeeId} className="rounded-lg border border-slate-200 p-4"><summary className="cursor-pointer text-sm font-semibold">{row.employee.code} · {row.employee.fullName} · Net {money(row.netPay)}</summary><div className="mt-4 grid gap-5 md:grid-cols-3">{[{ title: 'Earnings', fields: [...payrollEarnings, 'absenceDeduction', 'taxableCompensation'] as PayrollAmountField[] }, { title: 'Employee deductions', fields: payrollDeductions }, { title: 'Employer contributions', fields: payrollEmployerCosts }].map(group => <div key={group.title}><p className="text-sm font-semibold">{group.title}</p><dl className="mt-3 space-y-2">{group.fields.map(key => <div key={key} className="flex justify-between gap-3 text-xs leading-6"><dt className="text-slate-500">{payrollFieldLabels[key]}</dt><dd className="shrink-0">{money(row[key])}</dd></div>)}</dl></div>)}</div>{row.note && <p className="mt-3 text-sm text-slate-600">{row.note}</p>}<StatutoryEvidenceView evidence={row.statutoryEvidence} /><button className={`${secondary} mt-4`} onClick={() => { try { printPayslip(selected, row); setPrintError('') } catch (reason) { setPrintError(reason instanceof Error ? reason.message : 'Unable to print.') } }}><Printer className="size-4" />Print {selected.status === 'draft' ? 'draft ' : ''}payslip</button></details>)}</div>
      {printError && <p role="alert" className="mt-4 text-sm text-red-700">{printError}</p>}
      {selected.status === 'draft' && <div className="mt-6 border-t border-slate-200 pt-5">{selected.createdBy === company.membership?.uid ? <div><p className="text-sm leading-7 text-slate-600">Another Admin or Accounting Manager must independently approve this draft.</p><button className={`${secondary} mt-4`} onClick={() => setEditing(selected)} disabled={busy}>Edit payroll draft</button></div> : canApprove ? <form onSubmit={async event => { event.preventDefault(); await command({ action: 'approveRun', id: selected.id, expectedRevision: selected.version, expectedBooksRevision: company.revision, reviewNote }, 'Payroll approved and posted to the general ledger and compensation tax register.') }}><Field label="Independent review notes"><textarea className={`${inputClass} h-24 py-2`} required minLength={10} maxLength={3000} value={reviewNote} onChange={e => setReviewNote(e.target.value)} placeholder="Document pay, deductions, contributions, ATCs, and account checks." /></Field>{selected.employeeRevision !== employeeRevision && <p className="mt-3 text-sm text-amber-800">Employee records changed. The preparer must review and save the draft again.</p>}<p className="mt-3 text-sm leading-7 text-slate-500">Approval posts an accrual to the selected expense and liability accounts and adds employee compensation records to the tax register. It does not pay salaries or remit contributions.</p><button className={`${primary} mt-4`} disabled={busy || !selected.calculationsReviewed || selected.employeeRevision !== employeeRevision || !company.booksReady}>Approve and post payroll</button></form> : <p className="text-sm text-slate-500">An Admin or Accounting Manager must approve this draft.</p>}</div>}
      {selected.status === 'posted' && <div className="mt-5 rounded-lg bg-emerald-50 p-4 text-sm leading-7 text-emerald-900"><p>Approved and posted. Entry: {selected.entryId}</p><p>{selected.reviewNote}</p><Link className="mt-2 inline-block font-semibold underline" to="/accounting/journal">Open general journal</Link></div>}
    </section>}
  </div>
}
type DraftRow = { employeeId: string; note: string; statutoryEvidence?: PayrollStatutoryEvidence } & Record<PayrollAmountField, string>
function toDraftRow(row: PayrollRowInput): DraftRow { return { ...Object.fromEntries(payrollAmountFields.map(key => [key, (row[key] / 100).toFixed(2)])), employeeId: row.employeeId, note: row.note, ...(row.statutoryEvidence ? { statutoryEvidence: row.statutoryEvidence } : {}) } as DraftRow }
function draftRowInput(row: DraftRow): PayrollRowInput { return { ...Object.fromEntries(payrollAmountFields.map(key => [key, amount(row[key] || '0')])), employeeId: row.employeeId, note: row.note, ...(row.statutoryEvidence ? { statutoryEvidence: row.statutoryEvidence } : {}) } as PayrollRowInput }
function PayrollEditor({ run, employees, employeeRevision, runs, busy, command, close }: { run: SavedRun | null; employees: EmployeeRecord[]; employeeRevision: number; runs: SavedRun[]; busy: boolean; command: Command; close: () => void }) {
  const company = useCompany()!, [revision] = useState(employeeRevision), [error, setError] = useState(''), [changesReviewed, setChangesReviewed] = useState(!run || run.employeeRevision === employeeRevision)
  const [form, setForm] = useState<PayrollRunInput>(run || { reference: '', periodStart: `${today().slice(0, 7)}-01`, periodEnd: today(), payDate: today(), frequency: 'monthly', rows: [], accounts: { ...emptyPayrollAccounts }, calculationsReviewed: false, calculationNote: '' })
  const [calculationNotice, setCalculationNotice] = useState('')
  const [rows, setRows] = useState<DraftRow[]>(run ? run.rows.map(toDraftRow) : [])
  const rowInputs = () => rows.map(draftRowInput)
  const payload = () => ({ ...form, rows: rowInputs() })
  let preview: PayrollRun | null = null
  try { if (rows.length && form.reference.trim()) preview = calculatePayrollRun(payload(), employees, revision) } catch { /* The submit validation reports complete errors without interrupting typing. */ }
  const change = (key: keyof PayrollRunInput, value: unknown) => setForm(old => ({ ...old, ...(key !== 'calculationsReviewed' ? { calculationsReviewed: false } : {}), [key]: value }))
  function removeCalculationEvidence(employeeId: string) { setRows(old => old.map(row => { if (row.employeeId !== employeeId) return row; const next = { ...row }; delete next.statutoryEvidence; return next })); setForm(old => ({ ...old, calculationsReviewed: false })); setCalculationNotice('Calculation evidence removed; amounts remain editable. Document and review the manual basis before saving.') }
  function replaceCalculatedRow(value: PayrollRowInput, message: string) { setRows(old => old.map(row => row.employeeId === value.employeeId ? toDraftRow(value) : row)); setForm(old => ({ ...old, calculationsReviewed: false })); setCalculationNotice(message) }
  async function save(event: FormEvent) { event.preventDefault(); setError(''); try { const value = payload(); calculatePayrollRun(value, employees, revision); if (await command({ action: 'saveRun', id: run?.id, input: value, expectedRevision: run?.version || 0, expectedEmployeeRevision: revision }, 'Payroll draft saved for independent review.')) close() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Check payroll values.') } }
  return <form onSubmit={save} className="rounded-xl border border-blue-200 bg-white p-6"><div className="flex items-center justify-between"><h3 className="text-xl font-semibold">{run ? `Edit ${run.reference}` : 'Prepare a payroll run'}</h3><button type="button" onClick={close} aria-label="Close payroll editor"><X className="size-5" /></button></div>{error && <p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}{revision !== employeeRevision && <p role="alert" className="mt-4 text-sm text-amber-800">The employee register changed. Close and reopen this draft before saving.</p>}
    <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><Field label="Payroll reference"><input className={inputClass} value={form.reference} required maxLength={100} onChange={e => change('reference', e.target.value)} placeholder="PAY-2026-09" /></Field><Field label="Period start"><input type="date" className={inputClass} value={form.periodStart} required onChange={e => change('periodStart', e.target.value)} /></Field><Field label="Period end"><input type="date" className={inputClass} value={form.periodEnd} required onChange={e => change('periodEnd', e.target.value)} /></Field><Field label="Pay date / accrual date"><input type="date" className={inputClass} value={form.payDate} required onChange={e => change('payDate', e.target.value)} /></Field><Field label="Pay frequency"><select className={inputClass} value={form.frequency} onChange={e => change('frequency', e.target.value)}>{Object.entries(frequencyLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field></div>
    <div className="mt-5 flex flex-wrap items-center gap-3"><button type="button" className={secondary} onClick={() => { setForm(old => ({ ...old, calculationsReviewed: false })); setRows(employees.filter(employee => employee.active && employee.payFrequency === form.frequency && employee.startDate <= form.periodEnd && (!employee.endDate || employee.endDate >= form.periodStart)).map(employee => toDraftRow(blankPayrollRow(employee)))) }}>{rows.length ? 'Replace rows with eligible employees' : 'Load eligible employees'}</button><p className="text-xs text-slate-500">Loads basic pay only. Enter reviewed adjustments and deductions below.</p></div>
    {calculationNotice && <p role="status" className="mt-4 rounded-lg bg-blue-50 p-3 text-sm text-blue-900">{calculationNotice}</p>}
    <div className="mt-5 space-y-3">{rows.map((row, index) => { const employee = employees.find(value => value.id === row.employeeId); return <details key={row.employeeId} className="rounded-lg border border-slate-200 p-4"><summary className="cursor-pointer text-sm font-semibold">{employee?.code} · {employee?.fullName} <span className="font-normal text-slate-500">— edit payroll amounts</span></summary><div className="mt-5 grid gap-6 lg:grid-cols-3">{[{ title: 'Earnings & tax basis (PHP)', fields: [...payrollEarnings, 'absenceDeduction', 'taxableCompensation'] as PayrollAmountField[] }, { title: 'Employee deductions (PHP)', fields: payrollDeductions }, { title: 'Employer contributions (PHP)', fields: payrollEmployerCosts }].map(group => <div key={group.title}><h4 className="text-sm font-semibold text-blue-800">{group.title}</h4><div className="mt-4 space-y-3">{group.fields.map(key => <Field key={key} label={payrollFieldLabels[key]}><input className={inputClass} inputMode="decimal" value={row[key]} onChange={e => { setRows(old => old.map((value, idx) => idx === index ? { ...value, [key]: e.target.value } : value)); setForm(old => ({ ...old, calculationsReviewed: false })) }} /></Field>)}</div></div>)}</div>{employee && <StatutoryCalculator key={`${row.employeeId}:${form.periodStart}:${form.periodEnd}:${form.payDate}:${form.frequency}`} row={row} employee={employee} period={form} runs={runs} runId={run?.id} apply={replaceCalculatedRow} />}<StatutoryEvidenceView evidence={row.statutoryEvidence} />{row.statutoryEvidence && <button type="button" className="mt-3 text-xs font-semibold text-blue-700 underline" onClick={() => removeCalculationEvidence(row.employeeId)}>Use manual amounts instead — remove calculation evidence</button>}<div className="mt-5"><Field label="Employee payroll note"><input className={inputClass} value={row.note} maxLength={1000} onChange={e => setRows(old => old.map((value, idx) => idx === index ? { ...value, note: e.target.value } : value))} /></Field></div><button type="button" className="mt-4 text-sm font-medium text-red-700" onClick={() => setRows(old => old.filter(value => value.employeeId !== row.employeeId))}>Remove employee from this draft</button></details> })}</div>
    {preview && <div className="mt-5 grid gap-3 rounded-lg bg-blue-50 p-5 sm:grid-cols-4">{[['Gross pay', preview.totals.grossPay], ['Deductions', preview.totals.deductions], ['Net pay', preview.totals.netPay], ['Employer cost', preview.totals.totalCost]].map(([label, value]) => <div key={label as string}><p className="text-xs text-slate-500">{label}</p><p className="mt-2 font-semibold text-blue-900">{money(value as number)}</p></div>)}</div>}
    <details className="mt-6 rounded-lg border border-slate-200 p-4" open><summary className="cursor-pointer text-sm font-semibold">Posting accounts</summary><p className="mt-3 text-xs leading-6 text-slate-500">Choose the accounts to receive payroll accruals. Only categories with a nonzero amount require an account. Create specific liability accounts in the chart of accounts if needed.</p><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(payrollAccountLabels).map(([key, label]) => <Field key={key} label={label}><select className={inputClass} value={form.accounts[key as keyof PayrollAccounts]} onChange={e => setForm(old => ({ ...old, accounts: { ...old.accounts, [key]: e.target.value } }))}><option value="">Choose account</option>{company.books.accounts.filter(account => account.type === (key === 'salaryExpense' || key === 'employerExpense' ? 'Expense' : 'Liability') && !['1100', '2000', '2110'].includes(account.code)).map(account => <option key={account.code} value={account.code}>{account.code} · {account.name}</option>)}</select></Field>)}</div><Link to="/accounting/accounts" target="_blank" className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-blue-700">Open chart of accounts<ExternalLink className="size-3" /></Link></details>
    <div className="mt-5 space-y-4"><Field label="Calculation basis and review notes"><textarea className={`${inputClass} h-28 py-2`} value={form.calculationNote} maxLength={3000} onChange={e => change('calculationNote', e.target.value)} placeholder="Record applicable contribution tables, bases, cut-off allocation, tax/exemption treatment, ATCs, and adjustments." /></Field><label className="flex items-start gap-3 text-sm leading-7 text-slate-600"><input type="checkbox" className="mt-1.5 size-4" checked={form.calculationsReviewed} onChange={e => change('calculationsReviewed', e.target.checked)} /><span>I reviewed the earnings, deductions, employee and employer contributions, taxable compensation, ATCs, and posting accounts. All zero amounts are intentional for this period.</span></label>{run && run.employeeRevision !== revision && <label className="flex items-start gap-3 text-sm leading-7 text-amber-800"><input type="checkbox" className="mt-1.5 size-4" checked={changesReviewed} onChange={e => setChangesReviewed(e.target.checked)} /><span>The employee register changed after this draft was prepared. I have reviewed those changes and updated payroll amounts where necessary.</span></label>}</div>
    <div className="mt-6 flex gap-3"><button className={primary} disabled={busy || !rows.length || revision !== employeeRevision || !changesReviewed}>{busy ? 'Saving…' : 'Save payroll draft'}</button><button type="button" className={secondary} onClick={close}>Cancel</button></div>
  </form>
}
function StatutoryEvidenceView({ evidence }: { evidence?: PayrollStatutoryEvidence }) {
  if (!evidence) return null
  const monthly = evidence.monthly?.suggestion, withholding = evidence.withholding?.suggestion
  return <div className="mt-4 space-y-4 rounded-lg border border-blue-100 bg-blue-50 p-4"><p className="text-sm font-semibold text-blue-900">Saved calculation review</p><p className="text-xs leading-6 text-slate-600">The server recalculates these suggestions from the saved bases before saving and approving payroll. Tables checked {monthly?.verifiedOn || withholding?.verifiedOn}.</p>
    {monthly && <div><p className="text-sm font-semibold">Monthly contributions · {monthly.basis.contributionMonth}</p><dl className="mt-2 grid gap-2 text-xs sm:grid-cols-2">{[['SSS monthly compensation', monthly.basis.sssMonthlyCompensation], ['SSS salary credit', monthly.sss.monthlySalaryCredit], ['PhilHealth fixed monthly basic salary', monthly.basis.philhealthMonthlyBasicSalary], ['Pag-IBIG monthly fund salary', monthly.basis.pagibigMonthlyFundSalary], ['SSS regular employee / employer', `${money(monthly.sss.regularEmployee)} / ${money(monthly.sss.regularEmployer)}`], ['SSS provident employee / employer', `${money(monthly.sss.providentEmployee)} / ${money(monthly.sss.providentEmployer)}`]].map(([label, value]) => <div key={String(label)} className="flex justify-between gap-3"><dt className="text-slate-600">{label}</dt><dd className="font-medium">{typeof value === 'number' ? money(value) : value}</dd></div>)}</dl><p className="mt-2 text-xs leading-6 text-slate-600">{monthly.reviewNote}</p><p className="mt-1 text-xs text-slate-600">Full-month application and no other allocation confirmed.{monthly.philhealth.roundingDifference !== 0 && ' PhilHealth centavo rounding was explicitly confirmed.'}</p></div>}
    {withholding && <div><p className="text-sm font-semibold">Compensation withholding · {frequencyLabels[withholding.basis.frequency]}</p><p className="mt-2 text-xs leading-6 text-slate-600">Taxable compensation {money(withholding.basis.taxableCompensation)} · Fixed tax {money(withholding.fixedTax)} + {withholding.ratePercent}% of excess {money(withholding.excess)} = {money(withholding.withholdingTax)}.</p><p className="mt-1 text-xs leading-6 text-slate-600">{withholding.reviewNote}</p></div>}
    <details><summary className="cursor-pointer text-xs font-semibold text-blue-800">Official sources and calculation limits</summary><ul className="mt-3 space-y-2 text-xs leading-6 text-slate-600">{[...new Set([...(monthly?.warnings || []), ...(withholding?.warnings || [])])].map(warning => <li key={warning}>{warning}</li>)}</ul><div className="mt-3 flex flex-col gap-2">{[...(monthly?.sources || []), ...(withholding?.sources || [])].map(source => <a key={source.url} className="text-xs font-medium text-blue-700 underline" href={source.url} target="_blank" rel="noopener noreferrer">{source.title}</a>)}</div></details>
  </div>
}
function StatutoryCalculator({ row, employee, period, runs, runId, apply }: { row: DraftRow; employee: EmployeeRecord; period: PayrollPeriodContext; runs: SavedRun[]; runId?: string; apply: (value: PayrollRowInput, message: string) => void }) {
  const [sss, setSss] = useState(''), [philhealth, setPhilhealth] = useState(''), [pagibig, setPagibig] = useState(''), [monthlyNote, setMonthlyNote] = useState(''), [monthlyReviewed, setMonthlyReviewed] = useState(false), [noOther, setNoOther] = useState(false), [rounding, setRounding] = useState(false)
  const [taxable, setTaxable] = useState(''), [taxNote, setTaxNote] = useState(''), [taxReviewed, setTaxReviewed] = useState(false)
  const [monthly, setMonthly] = useState<MonthlyContributionSuggestion | null>(null), [withholding, setWithholding] = useState<CompensationWithholdingSuggestion | null>(null), [error, setError] = useState('')
  const amountFingerprint = JSON.stringify(payrollAmountFields.map(key => row[key]))
  useEffect(() => { setMonthly(null); setWithholding(null); setMonthlyReviewed(false); setTaxReviewed(false); setNoOther(false); setRounding(false) }, [amountFingerprint])
  let monthlyUnavailable = ''
  try { payrollFullContributionMonth(period, employee) } catch (reason) { monthlyUnavailable = reason instanceof Error ? reason.message : 'Review the payroll month.' }
  const month = period.periodStart.slice(0, 7)
  const prior = runs.find(run => run.id !== runId && run.status === 'posted' && run.rows.some(item => item.employeeId === employee.id) && ((run.periodStart <= period.periodEnd && run.periodEnd >= period.periodStart) || run.payDate.slice(0, 7) === month || run.rows.some(item => item.employeeId === employee.id && item.statutoryEvidence?.monthly?.suggestion.basis.contributionMonth === month)))
  if (prior) monthlyUnavailable = `Posted payroll ${prior.reference} covers or was paid in this month. Reconcile previous allocations and enter reviewed manual contributions.`
  const monthChange = (setter: (value: string) => void, value: string) => { setter(value); setMonthly(null); setNoOther(false); setRounding(false) }
  function monthlyInput() { return { contributionMonth: month, scope: 'ordinary_private_employee_full_month', basesReviewed: monthlyReviewed, reviewNote: monthlyNote, sssMonthlyCompensation: amount(sss), philhealthMonthlyBasicSalary: amount(philhealth), pagibigMonthlyFundSalary: amount(pagibig) } }
  function taxInput() { return { payDate: period.payDate, frequency: period.frequency, scope: 'regular_single_employer_period', basesReviewed: taxReviewed, reviewNote: taxNote, taxableCompensation: amount(taxable) } }
  function calculate(kind: 'monthly' | 'withholding') { setError(''); try { if (kind === 'monthly') { if (monthlyUnavailable) throw Error(monthlyUnavailable); setMonthly(suggestMonthlyContributions(monthlyInput())) } else setWithholding(suggestCompensationWithholding(taxInput())) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Check the reviewed calculation inputs.') } }
  function applySuggestion(kind: 'monthly' | 'withholding') { setError(''); try { const input = draftRowInput(row); if (kind === 'monthly') { if (monthlyUnavailable) throw Error(monthlyUnavailable); if (!monthly) throw Error('Preview the current monthly inputs first.'); const current = suggestMonthlyContributions(monthlyInput()); if (JSON.stringify(current.basis) !== JSON.stringify(monthly.basis)) throw Error('Inputs changed. Preview the calculation again.'); apply(applyMonthlyPayrollSuggestion(input, employee, period, current, noOther, rounding), 'Monthly contributions applied. Review taxable compensation and withholding again before approving payroll.') } else { if (!withholding) throw Error('Preview the current withholding inputs first.'); const current = suggestCompensationWithholding(taxInput()); if (JSON.stringify(current.basis) !== JSON.stringify(withholding.basis)) throw Error('Inputs changed. Preview the calculation again.'); apply(applyPayrollWithholdingSuggestion(input, employee, period, current), 'Reviewed taxable compensation and withholding applied to this payroll draft.') } } catch (reason) { setError(reason instanceof Error ? reason.message : 'Review the calculation before applying it.') } }
  return <details className="mt-5 rounded-xl border border-blue-200 bg-slate-50 p-4"><summary className="cursor-pointer text-sm font-semibold text-blue-800">Optional contribution and withholding calculator</summary><p className="mt-3 text-xs leading-6 text-slate-600">Reviewed tables as of {payrollStatutoryVerifiedOn}. Preview amounts, then choose Apply. All bases must be classified by your payroll reviewer; earnings are not automatically classified. Special classes, partial months, annualization, final pay and irregular compensation require manual calculation.</p>{error && <p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="space-y-4 rounded-lg border border-slate-200 bg-white p-4"><h4 className="text-sm font-semibold">Monthly contributions</h4><p className="text-xs leading-6 text-slate-500">Whole month: {month}. Apply is available only for a complete monthly payroll; it never divides contributions among cutoffs.</p>{monthlyUnavailable && <p className="rounded-md bg-amber-50 p-3 text-xs leading-6 text-amber-900">{monthlyUnavailable}</p>}
      <Field label="SSS monthly compensation (PHP)"><input className={inputClass} inputMode="decimal" value={sss} onChange={e => monthChange(setSss, e.target.value)} /></Field><Field label="PhilHealth fixed monthly basic salary (PHP)"><input className={inputClass} inputMode="decimal" value={philhealth} onChange={e => monthChange(setPhilhealth, e.target.value)} /></Field><p className="text-xs leading-6 text-slate-500">Use fixed basic before absences or unpaid time; exclude overtime, allowances, commissions, bonuses and 13th-month pay.</p><Field label="Pag-IBIG monthly fund salary (PHP)"><input className={inputClass} inputMode="decimal" value={pagibig} onChange={e => monthChange(setPagibig, e.target.value)} /></Field><Field label="Monthly contribution review basis"><textarea className={`${inputClass} h-20 py-2`} maxLength={1000} value={monthlyNote} onChange={e => monthChange(setMonthlyNote, e.target.value)} placeholder="Explain the three bases and supporting payroll records." /></Field>
      <label className="flex items-start gap-2 text-xs leading-6 text-slate-600"><input type="checkbox" className="mt-1 size-4 shrink-0" checked={monthlyReviewed} onChange={e => { setMonthlyReviewed(e.target.checked); setMonthly(null) }} /><span>I reviewed each basis and confirm ordinary private employment with one employer for the full month, excluding special coverage classes.</span></label><button type="button" className={secondary} disabled={Boolean(monthlyUnavailable) || !monthlyReviewed} onClick={() => calculate('monthly')}>Preview monthly contributions</button>
      {monthly && <div className="space-y-3 border-t border-slate-200 pt-4"><dl className="space-y-2">{Object.entries(monthly.monthlyAmounts).map(([key, value]) => <div className="flex justify-between gap-3 text-xs" key={key}><dt className="text-slate-600">{payrollFieldLabels[key as PayrollAmountField]}</dt><dd className="font-semibold">{money(value)}</dd></div>)}</dl><p className="text-xs text-slate-500">SSS salary credit {money(monthly.sss.monthlySalaryCredit)} · EC is employer-only.</p>{monthly.philhealth.roundingDifference !== 0 && <div className="rounded-md bg-amber-50 p-3 text-xs leading-6 text-amber-900"><p>Equal rounded PhilHealth shares total {money(monthly.philhealth.premium)}; rounding the unsplit premium gives {money(monthly.philhealth.calculatedUnsplitPremium)}. Confirm the assessment before applying.</p><label className="mt-2 flex items-start gap-2"><input type="checkbox" className="mt-1 size-4 shrink-0" checked={rounding} onChange={e => setRounding(e.target.checked)} /><span>I confirmed the agency assessment and equal-share rounding.</span></label></div>}<label className="flex items-start gap-2 text-xs leading-6 text-slate-600"><input type="checkbox" className="mt-1 size-4 shrink-0" checked={noOther} onChange={e => setNoOther(e.target.checked)} /><span>None of these monthly contributions has already been allocated, deducted or remitted for this employee, including outside this system. Apply the full month once.</span></label><button type="button" className={primary} disabled={!noOther || Boolean(monthlyUnavailable) || (monthly.philhealth.roundingDifference !== 0 && !rounding)} onClick={() => applySuggestion('monthly')}>Apply monthly contributions</button></div>}
    </section><section className="space-y-4 rounded-lg border border-slate-200 bg-white p-4"><h4 className="text-sm font-semibold">Tax withheld for this payday</h4><p className="text-xs leading-6 text-slate-500">{frequencyLabels[period.frequency]} · Pay date {period.payDate}. Enter taxable compensation after reviewing the applicable exclusions and deductions.</p><Field label="Reviewed taxable compensation for this period (PHP)"><input className={inputClass} inputMode="decimal" value={taxable} onChange={e => { setTaxable(e.target.value); setWithholding(null) }} /></Field><Field label="Compensation tax review basis"><textarea className={`${inputClass} h-24 py-2`} maxLength={1000} value={taxNote} onChange={e => { setTaxNote(e.target.value); setWithholding(null) }} placeholder="Explain taxable pay, exclusions and employee treatment." /></Field><label className="flex items-start gap-2 text-xs leading-6 text-slate-600"><input type="checkbox" className="mt-1 size-4 shrink-0" checked={taxReviewed} onChange={e => { setTaxReviewed(e.target.checked); setWithholding(null) }} /><span>This is regular taxable compensation from one employer for one ordinary pay period. I reviewed exclusions and deductions. Minimum-wage exemptions, supplementary pay, prior employers, final pay and annualization are not included.</span></label><button type="button" className={secondary} disabled={!taxReviewed} onClick={() => calculate('withholding')}>Preview withholding</button>
      {withholding && <div className="space-y-3 border-t border-slate-200 pt-4"><p className="text-xl font-semibold text-blue-900">{money(withholding.withholdingTax)}</p><p className="text-xs leading-6 text-slate-600">{money(withholding.fixedTax)} fixed tax + {withholding.ratePercent}% of {money(withholding.excess)} excess above {money(withholding.threshold)}.</p><p className="text-xs leading-6 text-slate-500">Apply replaces this row’s taxable compensation and withholding tax only.</p><button type="button" className={primary} onClick={() => applySuggestion('withholding')}>Apply reviewed withholding</button></div>}
    </section></div>
  </details>
}

function printPayslip(run: SavedRun, row: PayrollRow) {
  const escape = (value: unknown) => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]!)
  const win = window.open('', '_blank')
  if (!win) throw Error('Allow a print window for this site, then try again.')
  win.opener = null
  const lines = (fields: readonly PayrollAmountField[]) => fields.filter(key => row[key]).map(key => `<tr><td>${escape(payrollFieldLabels[key])}</td><td>${escape(money(row[key]))}</td></tr>`).join('')
  win.document.write(`<!doctype html><html lang="en"><head><title>${escape(run.reference)} · ${escape(row.employee.code)} payslip</title><style>body{font:14px Arial,sans-serif;color:#172b4d;max-width:720px;margin:40px auto;padding:20px}h1{font-size:24px}h2{font-size:18px;margin-top:28px}table{border-collapse:collapse;width:100%;margin-top:16px}td{padding:9px;border-bottom:1px solid #ddd}td:last-child{text-align:right}.net{padding:20px;background:#eaf3fb;margin-top:24px;font-size:20px}.meta{color:#526277;line-height:1.8}.draft{color:#a05c00;font-weight:bold}@media print{button{display:none}}@page{size:A4;margin:18mm}</style></head><body><h1>${escape(run.companyName)}</h1><p class="${run.status === 'draft' ? 'draft' : ''}">${run.status === 'draft' ? 'DRAFT PAYSLIP — NOT APPROVED' : 'PAYSLIP — POSTED PAYROLL ACCRUAL'}</p><h2>${escape(row.employee.fullName)}</h2><p class="meta">Employee ${escape(row.employee.code)} · ${escape(row.employee.department)}<br>Period ${escape(run.periodStart)} to ${escape(run.periodEnd)}<br>Pay / accrual date ${escape(run.payDate)} · Reference ${escape(run.reference)}</p><h2>Earnings</h2><table>${lines([...payrollEarnings, 'absenceDeduction'])}<tr><td><strong>Gross pay</strong></td><td>${escape(money(row.grossPay))}</td></tr></table><h2>Employee deductions</h2><table>${lines(payrollDeductions)}<tr><td><strong>Total deductions</strong></td><td>${escape(money(row.totalDeductions))}</td></tr></table><div class="net">Net pay: <strong>${escape(money(row.netPay))}</strong></div><p class="meta">Employer contributions: ${escape(money(row.employerContributions))}<br>${escape(row.note)}</p><p class="meta">This statement summarizes the recorded payroll. Salary payment and statutory remittances are handled separately.</p><button onclick="window.print()">Print / save as PDF</button></body></html>`)
  win.document.close()
}
