export const MAJOR_LGUS = [
  'Quezon City',
  'Manila',
  'Makati',
  'Taguig',
  'Pasig',
  'Mandaluyong',
  'Pasay',
  'Parañaque',
  'Las Piñas',
  'Muntinlupa',
  'Caloocan',
  'Marikina',
  'San Juan',
  'Valenzuela',
  'Malabon',
  'Navotas',
  'Cebu City',
  'Davao City',
  'Iloilo City',
  'Baguio',
  'Bacolod',
  'Cagayan de Oro',
  'Zamboanga City',
  'General Santos',
  'Antipolo',
  'Dasmariñas',
  'Bacoor',
  'Imus',
  'Calamba',
  'Santa Rosa',
  'Angeles City',
  'San Fernando, Pampanga',
  'Tarlac City',
  'Olongapo',
  'Legazpi',
  'Naga',
  'Puerto Princesa',
  'Butuan',
  'Iligan',
  'Tacloban',
  'Dipolog',
  'Pagadian',
  'Cotabato City',
  'Tagbilaran',
  'Dumaguete',
  'Roxas City',
  'Ormoc',
  'San Pablo',
  'Lucena',
  'Tuguegarao',
] as const
