import { ArrowRight, BookOpen, Building2, FileText, LifeBuoy, LockKeyhole, MessageCircle, User } from 'lucide-react'
import { Link } from 'react-router-dom'
import { ButtonLink } from '@/components/landing/ButtonLink'

const topics = [
  { id: 'account', icon: User, title: 'Your account', text: 'Sign in with your own email address and verify it before opening the workspace. Your name and personal taxpayer details can be updated in Settings.', to: '/settings', action: 'Open account settings' },
  { id: 'company', icon: Building2, title: 'Company access', text: 'Each user belongs to one company workspace. Joining requires the company code and an email-bound invitation from an Admin. Contact your Admin if an invitation expires or your role needs to change.', to: '/accounting/company', action: 'Open company settings' },
  { id: 'records', icon: BookOpen, title: 'Personal and company records', text: 'Income & Expenses and Tax Dues contain your personal workspace records. UBB Accounting contains the shared company books. Updating one workspace does not automatically update the other.', to: '/accounting/overview', action: 'Open UBB Accounting' },
  { id: 'filing', icon: FileText, title: 'Preparation and government filing', text: 'Accounting entries, draft returns, and a completed internal checklist are preparation records. Keep the acknowledgment from the relevant agency and separate proof of payment as evidence of the actual transaction.', to: '/tax-dues', action: 'Review tax obligations' },
]

export function HelpPage() {
  return <div className="bg-slate-50 text-slate-900"><section className="bg-[#103d72] text-white"><div className="mx-auto max-w-6xl px-6 py-14 md:py-20"><p className="text-sm font-semibold tracking-widest text-blue-200 uppercase">TaxPhil support</p><h1 className="mt-4 text-4xl font-semibold tracking-tight">A little guidance goes a long way.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-blue-100">Find your way around your account, company workspace, and records.</p></div></section><div className="mx-auto max-w-6xl px-6 py-12"><div className="grid gap-6 md:grid-cols-2">{topics.map(({ id, icon: Icon, title, text, to, action }) => <section key={id} id={id} className="scroll-mt-24 rounded-xl border border-slate-200 bg-white p-7"><div className="flex size-11 items-center justify-center rounded-lg bg-blue-50 text-blue-700"><Icon className="size-5" /></div><h2 className="mt-5 text-xl font-semibold">{title}</h2><p className="mt-3 text-sm leading-7 text-slate-600">{text}</p><Link to={to} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-blue-700">{action}<ArrowRight className="size-4" /></Link></section>)}</div>
    <section id="data" className="mt-8 scroll-mt-24 rounded-xl border border-slate-200 bg-white p-7 md:p-9"><div className="flex items-center gap-3"><LockKeyhole className="size-6 text-blue-700" /><h2 className="text-2xl font-semibold">Your data and access</h2></div><div className="mt-6 grid gap-8 md:grid-cols-2"><div><h3 className="font-semibold">What you enter in TaxPhil</h3><p className="mt-3 text-sm leading-7 text-slate-600">Account details, taxpayer profiles, recorded transactions, obligations, permit requests, and support conversations support the features you use. Company records are shared with active members according to their assigned role. Use individual accounts and keep invitation codes private.</p></div><div><h3 className="font-semibold">Review, export, or ask for help</h3><p className="mt-3 text-sm leading-7 text-slate-600">Use the export controls in your records and accounting workspace to keep copies. To ask about a correction, export, or deletion that you cannot complete in the app, contact the team and identify the relevant record. Avoid sending passwords, one-time codes, or unnecessary identity documents in chat.</p></div></div><p className="mt-7 border-t border-slate-100 pt-5 text-sm leading-7 text-slate-500">This page explains available product controls. It is not a published privacy policy or terms of service.</p></section>
    <section className="mt-8 rounded-xl border border-slate-200 bg-white p-7"><div className="flex items-center gap-3"><LifeBuoy className="size-6 text-blue-700" /><h2 className="text-2xl font-semibold">Common questions</h2></div><div className="mt-5 divide-y divide-slate-100">{[
      ['I cannot sign in. What should I do?', 'Use the password reset option on the login page. If the account needs email verification, follow the verification message or request another one. The team will never need your password or one-time code.'],
      ['Why is my workspace empty?', 'A new workspace starts without transactions. Check that you are signed into the correct account and, for UBB Accounting, the correct company. Sample preview records do not become live company data.'],
      ['Why does a page show a connection or access error?', 'Your session, account access, or a required service may need attention. Read the message on the page, then try signing out and signing in again. If it continues, send the page name and error text to support.'],
      ['Does an entry marked filed prove that BIR or SEC accepted it?', 'A status you record in TaxPhil is an internal record. Confirm the result with the relevant agency and retain the official acknowledgment and payment evidence.'],
      ['Is a meeting request immediately confirmed?', 'A request needs a response from the team. Check the meeting or support conversation for confirmed details before joining.'],
    ].map(([question, answer]) => <details key={question} className="py-4"><summary className="cursor-pointer text-sm font-semibold text-slate-900">{question}</summary><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-600">{answer}</p></details>)}</div></section>
    <div className="mt-8 flex flex-col gap-5 rounded-xl bg-[#103d72] p-7 text-white sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-semibold">Still need a hand?</h2><p className="mt-2 text-sm leading-7 text-blue-100">Sign in to send a question to the TaxPhil team.</p></div><ButtonLink to="/connect" className="bg-white text-blue-800 hover:bg-blue-50"><MessageCircle className="size-4" />Contact support</ButtonLink></div>
  </div></div>
}
