import { ArrowRight, BookOpen, Building2, CalendarDays, Check, CheckCircle2, FileText, Layers3, MessageCircle, Receipt, ShieldCheck, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { ButtonLink } from '@/components/landing/ButtonLink'
import { OnlineServicesSection } from '@/components/landing/OnlineServicesSection'

const features = [
  { icon: Layers3, title: 'One company workspace', description: 'Bring invoices, bills, journals, and reports together in UBB Accounting.', to: '/accounting/overview' },
  { icon: Users, title: 'Clear responsibilities', description: 'Give your Admin, Accounting Manager, Accountant, and Viewer the access they need.', to: '/accounting/team' },
  { icon: Receipt, title: 'Records you can follow', description: 'Track income, expenses, receivables, and payables with references that make reviews easier.', to: '/income-expenses' },
  { icon: CheckCircle2, title: 'Review before posting', description: 'Prepare entries, review accountant submissions, and keep a history of changes.', to: '/accounting/approvals' },
  { icon: CalendarDays, title: 'Compliance preparation', description: 'Organize obligations and consult official sources as you prepare your filings.', to: '/accounting/compliance' },
  { icon: MessageCircle, title: 'A team to connect with', description: 'Send your questions and discuss the accounting or advisory support you need.', to: '/connect' },
]
const services = [
  { title: 'Business registration', text: 'Discuss your business structure, registration requirements, and the steps that apply to your setup.', icon: Building2 },
  { title: 'Accounting support', text: 'Explore help with bookkeeping, financial reports, and a repeatable review process.', icon: BookOpen },
  { title: 'Fractional CFO', text: 'Discuss financial planning, reporting, and advisory support for your next stage of growth.', icon: Layers3 },
  { title: 'Tax consultation', text: 'Bring your questions about registration, records, and filing preparation to the team.', icon: MessageCircle },
]

export function LandingPage() {
  return (
    <div className="bg-slate-50 text-slate-900">
      <section className="border-b border-slate-200 bg-white"><div className="mx-auto grid max-w-6xl items-center gap-12 px-6 py-14 md:py-20 lg:grid-cols-[1fr_1fr] lg:gap-16">
        <div><p className="inline-flex items-center gap-2 rounded-full border border-blue-100 bg-blue-50 px-3 py-1.5 text-xs font-semibold text-blue-700"><span className="size-1.5 rounded-full bg-blue-600" />FOR PHILIPPINE BUSINESSES</p><h1 className="mt-6 text-4xl font-semibold leading-[1.12] tracking-tight md:text-5xl lg:text-[54px]">Your business.<br />Your numbers.<br /><span className="text-blue-700">A clearer picture.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Bring your records, accounting, and compliance preparation into one organized workspace. Move your business forward with TaxPhil.</p><div className="mt-8 flex flex-wrap gap-3"><ButtonLink size="lg" to="/signup" className="h-12 bg-blue-700 px-6 text-white hover:bg-blue-800">Create your workspace<ArrowRight className="size-4" /></ButtonLink><ButtonLink size="lg" to="/#how-it-works" variant="outline" className="h-12 px-6">See how it works</ButtonLink></div><div className="mt-7 flex flex-wrap gap-x-5 gap-y-2 text-sm text-slate-500"><span className="flex items-center gap-1.5"><Check className="size-4 text-blue-600" />Company access controls</span><span className="flex items-center gap-1.5"><Check className="size-4 text-blue-600" />Philippine peso records</span></div></div>
        <div className="relative"><div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-xl shadow-blue-950/5"><div className="flex items-center justify-between bg-[#103d72] px-5 py-4 text-white"><p className="text-sm font-semibold">UBB Accounting</p><span className="rounded bg-white/10 px-2 py-1 text-[11px] text-blue-100">WORKSPACE OVERVIEW</span></div><div className="border-b border-slate-100 px-5 py-4"><p className="text-lg font-semibold">Everything in its place.</p><p className="mt-1 text-sm text-slate-500">A connected view of your company</p></div><div className="grid grid-cols-2 gap-3 p-5">{[{ icon: FileText, label: 'Invoices & bills', detail: 'Keep track of what is due' }, { icon: BookOpen, label: 'Books & reports', detail: 'Understand your numbers' }, { icon: Users, label: 'Your team', detail: 'The right access for each role' }, { icon: ShieldCheck, label: 'Compliance', detail: 'Know what needs review' }].map(({ icon: Icon, label, detail }) => <div key={label} className="rounded-lg border border-slate-200 p-4"><Icon className="size-5 text-blue-600" /><p className="mt-3 text-sm font-semibold">{label}</p><p className="mt-1 text-xs leading-5 text-slate-500">{detail}</p></div>)}</div><div className="mx-5 mb-5 rounded-lg bg-slate-50 p-4"><div className="flex flex-wrap items-center gap-2 text-xs font-medium text-slate-600"><span className="rounded bg-white px-2 py-1.5">Prepare</span><ArrowRight className="size-3 text-blue-500" /><span className="rounded bg-white px-2 py-1.5">Review</span><ArrowRight className="size-3 text-blue-500" /><span className="rounded bg-blue-50 px-2 py-1.5 text-blue-700">Post &amp; report</span></div></div></div><p className="mt-3 text-center text-xs text-slate-400">An overview of the workspace features</p></div>
      </div></section>
      <section id="features" className="mx-auto max-w-6xl scroll-mt-24 px-6 py-16 md:py-20"><div className="max-w-2xl"><p className="text-sm font-semibold text-blue-700">LESS FRICTION. MORE CLARITY.</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">Make the daily work work for you.</h2><p className="mt-4 leading-7 text-slate-600">Connected tools for the records, people, and decisions behind your business.</p></div><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{features.map(({ icon: Icon, title, description, to }) => <Link key={title} to={to} className="group rounded-xl border border-slate-200 bg-white p-6 transition-colors hover:border-blue-400"><div className="flex items-center justify-between"><div className="flex size-11 items-center justify-center rounded-lg bg-blue-50 text-blue-700"><Icon className="size-5" /></div><ArrowRight className="size-4 text-slate-300 group-hover:text-blue-600" /></div><h3 className="mt-5 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{description}</p></Link>)}</div></section>
      <OnlineServicesSection />
      <section id="plans" className="mx-auto max-w-6xl scroll-mt-24 px-6 py-16 md:py-20"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-semibold text-blue-700">PEOPLE BEHIND THE PLATFORM</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">Support for your next step.</h2></div><ButtonLink to="/about" variant="outline">Meet our team<ArrowRight className="size-4" /></ButtonLink></div><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{services.map(({ title, text, icon: Icon }) => <article key={title} className="flex flex-col rounded-xl border border-slate-200 bg-white p-6"><Icon className="size-6 text-blue-600" /><h3 className="mt-5 text-lg font-semibold">{title}</h3><p className="mt-3 flex-1 text-sm leading-7 text-slate-600">{text}</p><ButtonLink to="/connect" variant="outline" className="mt-6 justify-between">Discuss your needs<ArrowRight className="size-4" /></ButtonLink></article>)}</div><p className="mt-5 text-sm leading-7 text-slate-500">The team will confirm the scope, availability, and any fees before you proceed.</p></section>
      <section id="how-it-works" className="scroll-mt-24 border-y border-slate-200 bg-white py-16 md:py-20"><div className="mx-auto max-w-6xl px-6"><p className="text-sm font-semibold text-blue-700">FROM SETUP TO REVIEW</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">A clear path through your work.</h2><div className="mt-10 grid gap-8 md:grid-cols-3">{[{ title: 'Set up your workspace', text: 'Create an account, verify your email, and complete your company profile or accept an invitation.', to: '/signup', cta: 'Get started' }, { title: 'Build the records', text: 'Record your transactions, organize invoices and bills, and review entries with your team.', to: '/accounting/overview', cta: 'Open accounting' }, { title: 'Review and prepare', text: 'Check your reports, review applicable obligations, and keep your official filing evidence.', to: '/accounting/compliance', cta: 'Review compliance' }].map((step, index) => <div key={step.title}><span className="flex size-10 items-center justify-center rounded-full bg-blue-50 text-sm font-semibold text-blue-700">0{index + 1}</span><h3 className="mt-5 text-lg font-semibold">{step.title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{step.text}</p><Link to={step.to} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-blue-700">{step.cta}<ArrowRight className="size-4" /></Link></div>)}</div></div></section>
      <section id="free-consultation" className="scroll-mt-24 bg-[#103d72] py-14 text-white md:py-20"><div className="mx-auto flex max-w-6xl flex-col gap-8 px-6 md:flex-row md:items-center md:justify-between"><div className="max-w-2xl"><p className="text-sm font-semibold text-blue-200">LET’S MOVE YOUR BUSINESS FORWARD</p><h2 className="mt-4 text-3xl font-semibold tracking-tight">Your next step starts with a conversation.</h2><p className="mt-4 leading-7 text-blue-100">Tell us where you are today and what you need help with. We’ll help you identify a practical way forward.</p></div><ButtonLink to="/connect" size="lg" className="h-12 shrink-0 bg-white px-6 text-blue-800 hover:bg-blue-50">Contact our team<ArrowRight className="size-4" /></ButtonLink></div></section>
    </div>
  )
}
