import { ArrowRight, CalendarClock } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useTaxStore } from '@/store/useTaxStore'
import { formatCurrency } from '@/lib/utils'
import { deadlineStatus, trackingDateLabel, trackingStatusLabel } from '@/lib/tax-workflows'

export function TaxDuesSummaryCard() {
  const deadlines = useTaxStore(state => state.deadlines), loading = useTaxStore(state => state.loading), error = useTaxStore(state => state.error)
  const next = [...deadlines].filter(item => item.status !== 'filed').sort((a, b) => a.dueDate.localeCompare(b.dueDate))[0]
  return <section className="overflow-hidden rounded-xl border border-[#dce5ed] bg-white text-[#243746]"><div className="flex items-start justify-between gap-4 border-b border-[#e6ecf2] p-5"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-[#60748a]">Personal tax tracker</p><h2 className="mt-2 text-lg font-semibold">{loading ? 'Loading obligations…' : error ? 'Records need attention' : next ? next.title : 'No pending records'}</h2></div><CalendarClock className="size-5 shrink-0 text-[#087cc1]" /></div><div className="p-5">{loading ? <p role="status" className="text-sm text-[#60748a]">Checking your saved schedule.</p> : error ? <p role="alert" className="text-sm text-red-800">{error}</p> : next ? <><div className="flex flex-wrap items-center gap-2"><span className="rounded-md bg-[#eaf4fa] px-2.5 py-1 text-xs font-medium text-[#087cc1]">{next.formType}</span><span className="text-xs text-[#60748a]">{trackingStatusLabel[deadlineStatus(next)]} · {next.taxPeriod || 'Period not specified'}</span></div><div className="mt-5 grid grid-cols-2 gap-4"><div><p className="text-xs text-[#60748a]">Recorded amount due</p><p className="mt-2 text-xl font-semibold tabular-nums">{formatCurrency(next.amountDue)}</p></div><div><p className="text-xs text-[#60748a]">Recorded due date</p><p className="mt-2 font-medium">{trackingDateLabel(next.dueDate)}</p></div></div></> : <p className="text-sm leading-6 text-[#60748a]">Add the obligations confirmed for your registration. An empty tracker does not establish that no return is due.</p>}</div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-[#e6ecf2] px-5 py-4"><p className="text-xs text-[#60748a]">Track dates and record filing evidence.</p><Link to={next ? '/tax-dues' : '/tax-dues?new=1'} className="inline-flex items-center gap-2 text-sm font-medium text-[#087cc1]">{next ? 'Manage obligations' : 'Add obligation'}<ArrowRight className="size-4" /></Link></div></section>
}
